blueprint:
  name: Predictive Power Control
  description: "# Avoid capacity tariff on electric consumption in Flanders\n\n**Version:
    1.0**\n\n**Summary**  \n  This automation aims to reduce the cost of the capacity
    tariff in Flanders by temporarily switching off certain appliances.  \n  The most
    obvious candidates are appliances that generate heat and can be turned off and
    on without issues  \n  (e.g., water heater, dryer, washing machine, electric heater,
    dishwasher, car charger, etc.).  \n\n\n**More information about the capacity tariff**
    \ \n  - https://www.youtube.com/watch?v=FgdXC210Dx4  \n  - https://www.vlaamsenutsregulator.be/nl/veelgestelde-vragen/hoeveel-capaciteitstarief-betaalt-u-voor-een-kilowatt
    \ \n\n\n**Prerequisites**  \n  - A sensor that reports your average power consumption
    over 15 minutes (e.g., Homewizard P1 meter)  \n  - A smart plug that can be turned
    on/off and reports the appliance’s power consumption  \n  - Appliances that can
    be turned on/off without malfunctioning  \n  - By default, these appliances should
    remain switched on at all times  \n\n\n**How to configure**  \n  - Set the **“Power
    sensor”** to `p1_meter_average_demand` of your P1 meter.  \n  - Set the **“Power
    threshold”** to the desired value. The automation will attempt to switch off devices
    if you risk surpassing this threshold.  \n  - Set the **“Power threshold for appliances”**
    to a value below which the appliance will be ignored by the automation.  \n    Typically,
    you don’t want to turn off the dishwasher, washing machine, etc., if they are
    not contributing significantly to overall power consumption.  \n  - Add the entity
    IDs for switches and their corresponding power sensors in YAML notation in the
    **“Devices to Control”**\n    You can find the entity ID by clicking on the switch
    or power sensor label, then on the gear icon. They must be provided in YAML format.\n\n
    \   Example:\n\n      \\- power_sensor: sensor.plug_washing_machine_power\n         switch:
    switch.plug_washing_machine\n      \\- power_sensor: sensor.plug_dishwasher_power\n
    \        switch: switch.plug_dishwasher\n\n\n**How it works**  \n  - The automation
    runs every 5 minutes.  \n  - It checks the current average demand and estimates
    the average demand at the end of the 15-minute interval.  \n  - If the estimated
    demand surpasses the **Power threshold**, it will turn off all appliances consuming
    more than the **Power threshold for appliances**.  \n  - If the estimated average
    demand is below the **Power threshold**, all previously switched-off devices will
    be turned on again.\n"
  domain: automation
  input:
    power_sensor:
      name: Power sensor
      description: Sensor tracking average power consumption over every quarter of
        an hour (e.g. p1_meter_average_demand).
      selector:
        entity:
          domain:
          - sensor
          device_class:
          - power
          reorder: false
          multiple: false
    threshold:
      name: Power threshold (W)
      description: Threshold in Watts to trigger power-off. If the p1_meter_average_demand
        is calculated to go over this value during the current quarter of an hour
        it will switch the devices off.
      default: 2200
      selector:
        number:
          min: 500.0
          max: 10000.0
          step: 50.0
          unit_of_measurement: W
          mode: slider
    power_threshold:
      name: Power threshold for appliances (W)
      description: If an appliance consumes less than this it is not powered off.
        This is used to not turn off appliances that are not consuming a lot of power.
      default: 100
      selector:
        number:
          min: 1.0
          max: 3500.0
          step: 1.0
          unit_of_measurement: W
          mode: slider
    devices:
      name: Devices to Control
      description: "List of devices (switches) with associated power sensors. This
        is a map where each entry contains:\n  - power_sensor: sensor entity\n  -
        switch: the switch to control\n  \nexample:\n  \\- power_sensor: sensor.plug_washing_machine_power\n
        \    switch: switch.plug_washing_machine\n  \\- power_sensor: sensor.plug_dishwasher_power\n
        \    switch: switch.plug_dishwasher\n"
      default: []
      selector:
        object:
          multiple: false
  source_url: https://github.com/ToinneGuust/Capacity-tariff-disable-appliances/blob/main/Capacity-tariff-disable-appliances.yaml
triggers:
- trigger: time_pattern
  minutes: /5
variables:
  sensor_entity: !input power_sensor
  threshold: !input threshold
  power_threshold: !input power_threshold
  minutes_now: '{{ now().minute % 15 | float(0) }}'
  current_value: '{{ states(sensor_entity) | float(0) }}'
  effective_minutes: '{{ 1 if minutes_now == 0 else minutes_now }}'
  predicted_value: '{{ ((current_value | float) / (effective_minutes | float) * 15)
    if minutes_now != 0 else 0 }}'
  device_list: !input devices
conditions: []
actions:
- if:
  - condition: template
    value_template: '{{ predicted_value > threshold and minutes_now != 0 }}'
  then:
  - repeat:
      for_each: '{{ device_list }}'
      sequence:
      - if:
        - condition: template
          value_template: '{{ states(repeat.item.power_sensor) | float(0) > power_threshold
            }}'
        then:
        - action: switch.turn_off
          target:
            entity_id: '{{ repeat.item.switch }}'
  else:
  - repeat:
      for_each: '{{ device_list }}'
      sequence:
      - action: switch.turn_on
        target:
          entity_id: '{{ repeat.item.switch }}'
- action: logbook.log
  data:
    name: Power Prediction Debug
    message: 'Current: {{ current_value }} W | Minutes: {{ minutes_now }} | Predicted:
      {{ predicted_value | round(2) }} W

      '
mode: single
trace:
  stored_traces: 300
