- binary_sensor:
    - name: Afkoeling gewenst
      unique_id: 61efbf71-ab3f-4e70-8d0f-81eff1e49d46
      state: >
        {{ (states('sensor.gemiddelde_temp_beneden') | float(0)) > (states('sensor.buiten_temperatuur') | float(0)) and 
            states('sensor.gemiddelde_temp_beneden') | float(0) > 25 }}
      icon: >
        {% if (states('sensor.gemiddelde_temp_beneden') | float(0)) > (states('sensor.buiten_temperatuur') | float(0)) and 
            states('sensor.gemiddelde_temp_beneden') | float(0) > 25 %}
          mdi:fan
        {% else %}
          mdi:fan-off
        {% endif %}
    
    - name: "Kans op Aanvriezen"
      unique_id: a562950c-c161-4617-ac9c-0eb5f6b0b745
      state: >
        {% set tmin = states('sensor.min_temperatuur_buiten_voorspelling_12u') | float %}
        {% if states("sensor.poort_luchtvochtigheid") not in ["unavailable", "unknown"] -%}
          {% set rh = states('sensor.poort_luchtvochtigheid') | float(0) %}
        {% else -%}
          {% set rh = states('sensor.luchtvochtigheid') | float(0) %}
        {% endif %}
        {% if states("sensor.buiten_dauwpunt") not in ["unavailable", "unknown"] -%}
          {% set dp = states('sensor.buiten_dauwpunt') | float(0) %}
        {% else -%}
          {% set dp = states('sensor.tomorrow_io_home_dew_point') | float(0) %}
        {% endif %}
        {% set wind = states('sensor.windsnelheid') | float %}
        {% set clouds = states('sensor.tomorrow_io_home_cloud_cover') | float %}

        {{ tmin < 1 and rh > 85 and (tmin - dp) < 2 and wind < 3 and clouds < 30 }}
      device_class: cold

    - name: Thermostat day mode
      unique_id: 78310cea-5406-404f-a065-fc7bcd579dc1
      state: >
        {{ states("alarm_control_panel.ha_alarm") is not in ["armed_night", "armed_away"] }}

    - name: "Condensatie Alarm Keuken"
      unique_id: cond_alarm_keuken
      state: >
        {% set marge = states('sensor.condensatie_marge_keuken') | float(99) %}
        {{ marge < 1 }}
      device_class: moisture
    
    - name: "Condensatie Alarm Noor"
      unique_id: cond_alarm_noor
      state: >
        {% set marge = states('sensor.condensatie_marge_noor') | float(99) %}
        {{ marge < 1 }}
      device_class: moisture
    
    - name: "Condensatie Alarm Slaapkamer"
      unique_id: cond_alarm_slaapkamer
      state: >
        {% set marge = states('sensor.condensatie_marge_slaapkamer') | float(99) %}
        {{ marge < 1 }}
      device_class: moisture
    
    - name: "Condensatie Alarm Fien"
      unique_id: cond_alarm_fien
      state: >
        {% set marge = states('sensor.condensatie_marge_fien') | float(99) %}
        {{ marge < 1 }}
      device_class: moisture

    - name: Buiten fris genoeg
      unique_id: 5c88bc6c-e453-4ea6-acbb-1eb5bbff493e
      device_class: cold
      state: >
        {{ states('sensor.buitentemperatuur_gefilterd') | float(default=0) < 25 }}

    - name: Verluchting afkoeling
      unique_id: 29b8677e-24fd-43c3-b81d-e8a2a7cac149
      device_class: cold
      state: >
        {{ is_state('input_boolean.verluchting_afkoeling', 'on') }}

    - name: Bathroom humidity rising template
      unique_id: 8b0ef76e-b2b4-4215-b84b-a9807032b956
      icon: mdi:water-percent
      state: >
        {{ states("sensor.badkamer_luchtvochtigheid_stats") | float(default=0) >= 7 | float(default=0)}}

    - name: Bathroom humidity falling template
      unique_id: 4474709e-2bf0-49a1-9d8c-f294c4895194
      icon: mdi:water-percent
      state: >
        {{ states("sensor.badkamer_luchtvochtigheid_stats") | float(default=0) <= -5 | float(default=0)}}
    # - name: keuken_humidity_rising_template
    #   unique_id: 5b823bf5-57cb-43a2-b98c-5eb8809cc41e
    #   icon: mdi:water-percent
    #   state : >
    #     {{ states("sensor.keuken_luchtvochtigheid_stats") | float(default=0) >= 7 | float(default=0)}}
    # - name: keuken_humidity_falling_template
    #   unique_id: 5c1b1e0d-4ed8-4d0f-99c1-04948d78e90e
    #   icon: mdi:water-percent
    #   state : >
    #     {{ states("sensor.keuken_luchtvochtigheid_stats") | float(default=0) <= -5 | float(default=0)}}
