- binary_sensor:
    - name: Keuken
      unique_id: cff13e1f-7343-4bf2-8627-da5930729e4e
      state: >
        {{ is_state('binary_sensor.keuken_moving', 'on') or is_state("binary_sensor.keuken_still", 'on') }}
      