input_number:
  error_adaboost:
    min: 0
    max: 24
    step: 0.001
    mode: box
  error_gradientboosting:
    min: 0
    max: 24
    step: 0.001
    mode: box
  error_extratrees:
    min: 0
    max: 24
    step: 0.001
    mode: box
  error_randomforest:
    min: 0
    max: 24
    step: 0.001
    mode: box
  error_svr:
    min: 0
    max: 24
    step: 0.001
    mode: box
  error_decisiontree:
    min: 0
    max: 24
    step: 0.001
    mode: box
  error_kneighbors:
    min: 0
    max: 24
    step: 0.001
    mode: box
  error_elasticnet:
    min: 0
    max: 24
    step: 0.001
    mode: box
  error_lasso:
    min: 0
    max: 24
    step: 0.001
    mode: box
  error_ridge:
    min: 0
    max: 24
    step: 0.001
    mode: box
  error_linear:
    min: 0
    max: 24
    step: 0.001
    mode: box
