wifi:
  networks:
    - ssid: !secret ssid-esphome
      password: !secret password-esphome

  power_save_mode: none
  fast_connect: true
  ap:
    ssid: ${upper_devicename}
    password: !secret password
    ap_timeout: 2min

  reboot_timeout: 5min

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${upper_devicename} IP
    ssid:
      name: ${upper_devicename} SSID
      id: ssid
    bssid:
      name: ${upper_devicename} BSSID
