doorbell_notification:
  sequence:
    - action: notify.iedereen
      data:
        title: Deurbel
        message: Ding dong! Er staat iemand aan de voordeur!
        data:
          attachment:
            content-type: jpeg
            url: http://tiptag.com.ar/wp-content/uploads/2018/06/timbre1.jpg
          push:
            sound: "House-bell-sound-effect.wav"
