## emhass_timestep
naive_mpc_optim:
  url: http://192.168.6.54:5003/action/naive-mpc-optim
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: "{{ payload }}"

publish_data:
  url: http://192.168.6.54:5003/action/publish-data
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
      "publish_prefix": "{{ prefix }}"
    }

test_naive_mpc_optim:
  url: http://192.168.5.21:5000/action/naive-mpc-optim
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: "{{ payload }}"

test_publish_data:
  url: http://192.168.5.21:5000/action/publish-data
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
      "publish_prefix": "{{ prefix }}"
    }

predict_epex_prices:
  url: https://epexpredictor.batzill.com/prices?hours=50&surcharge=0&taxPercent=0&region=BE&evaluation=false&unit=EUR_PER_KWH&hourly=false&timezone=Europe%2FBrussels
  method: GET
  timeout: 60
  content_type: "application/json"
