fit_heating_hours:
  url: http://192.168.6.54:5003/action/regressor-model-fit
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
      "csv_file": "prediction.csv",
      "features":["dd", "solar", "buiten_gisteren_mean", "beneden_gisteren_mean", "max_setpoint"],
      "target": "hour",
      "regression_model": "{{ regression_model }}",
      "model_type": "{{ model_type }}",
      "timestamp": "timestamp",
      "date_features": ["month", "day_of_week"]
    }

predict_heating_hours:
  url: http://192.168.6.54:5003/action/regressor-model-predict
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
      "model_type": "{{ model_type }}",
      "mlr_predict_entity_id": "{{ mlr_predict_entity_id }}",
      "mlr_predict_unit_of_measurement": "h",
      "mlr_predict_friendly_name": "{{ mlr_predict_friendly_name }}",
      "new_values": [{{states("sensor.degree_day_prediction")}}, {{states("sensor.open_meteo_voorspelling_vandaag")}}, {{buiten_temp}}, {{binnen_temp}}, {{max_setpoint}}, {{now().month}}, {{now().weekday()}}]
    }

