fit_heating_hours:
  url: http://localhost:5003/action/regressor-model-fit
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
    "csv_file": "prediction.csv",
    "features":["dd", "solar", "buiten_gisteren_mean", "beneden_gisteren_mean"],
    "target": "hour",
    "regression_model": "RandomForestRegressor",
    "model_type": "heating_dd",
    "timestamp": "timestamp",
    "date_features": ["month", "day_of_week"]
    }

predict_heating_hours:
  url: http://localhost:5003/action/regressor-model-predict
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
      "model_type": "heating_dd",
      "mlr_predict_entity_id": "sensor.voorspelde_uren_randomforest",
      "mlr_predict_unit_of_measurement": "h",
      "mlr_predict_friendly_name": "Voorspelde uren",
      "new_values": [{{states("sensor.degree_day_prediction")}}, {{states("sensor.open_meteo_voorspelling_vandaag")}}, {{buiten_temp}}, {{binnen_temp}}, {{now().month}}, {{now().weekday()}}]
    }

# fit_heating_hours_test:
#   url: http://192.168.5.21:5000/action/regressor-model-fit
#   method: POST
#   timeout: 300
#   content_type: "application/json"
#   payload: >-
#     {
#     "csv_file": "prediction.csv",
#     "features":["dd", "solar", "buiten_gisteren_mean", "beneden_gisteren_mean"],
#     "target": "hour",
#     "regression_model": "RandomForestRegressor",
#     "model_type": "heating_dd",
#     "timestamp": "timestamp",
#     "date_features": ["month", "day_of_week"]
#     }

# predict_heating_hours_test:
#   url: http://192.168.5.21:5000/action/regressor-model-predict
#   method: POST
#   timeout: 300
#   content_type: "application/json"
#   payload: >-
#     {
#       "model_type": "heating_dd",
#       "mlr_predict_entity_id": "sensor.voorspelde_uren_test",
#       "mlr_predict_unit_of_measurement": "h",
#       "mlr_predict_friendly_name": "Voorspelde uren",
#       "new_values": [{{states("sensor.degree_day_prediction")}}, {{states("sensor.open_meteo_voorspelling_vandaag")}}, {{buiten_temp}}, {{binnen_temp}}, {{now().month}}, {{now().weekday()}}]
#     }

fit_heating_hours_gradientboosting:
  url: http://localhost:5003/action/regressor-model-fit
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
    "csv_file": "prediction.csv",
    "features":["dd", "solar", "buiten_gisteren_mean", "beneden_gisteren_mean"],
    "target": "hour",
    "regression_model": "GradientBoostingRegressor",
    "model_type": "heating_dd_gradientboosting",
    "timestamp": "timestamp",
    "date_features": ["month", "day_of_week"]
    }

predict_heating_hours_gradientboosting:
  url: http://localhost:5003/action/regressor-model-predict
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
      "model_type": "heating_dd_gradientboosting",
      "mlr_predict_entity_id": "sensor.voorspelde_uren_gradientboosting",
      "mlr_predict_unit_of_measurement": "h",
      "mlr_predict_friendly_name": "Voorspelde uren GradientBoosting",
      "new_values": [{{states("sensor.degree_day_prediction")}}, {{states("sensor.open_meteo_voorspelling_vandaag")}}, {{buiten_temp}}, {{binnen_temp}}, {{now().month}}, {{now().weekday()}}]
    }

fit_heating_hours_adaboost:
  url: http://localhost:5003/action/regressor-model-fit
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
    "csv_file": "prediction.csv",
    "features":["dd", "solar", "buiten_gisteren_mean", "beneden_gisteren_mean"],
    "target": "hour",
    "regression_model": "AdaBoostRegressor",
    "model_type": "heating_dd_adaboost",
    "timestamp": "timestamp",
    "date_features": ["month", "day_of_week"]
    }

predict_heating_hours_adaboost:
  url: http://localhost:5003/action/regressor-model-predict
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
      "model_type": "heating_dd_adaboost",
      "mlr_predict_entity_id": "sensor.voorspelde_uren_adaboost",
      "mlr_predict_unit_of_measurement": "h",
      "mlr_predict_friendly_name": "Voorspelde uren AdaBoost",
      "new_values": [{{states("sensor.degree_day_prediction")}}, {{states("sensor.open_meteo_voorspelling_vandaag")}}, {{buiten_temp}}, {{binnen_temp}}, {{now().month}}, {{now().weekday()}}]
    }

fit_heating_hours_extratrees:
  url: http://localhost:5003/action/regressor-model-fit
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
    "csv_file": "prediction.csv",
    "features":["dd", "solar", "buiten_gisteren_mean", "beneden_gisteren_mean"],
    "target": "hour",
    "regression_model": "ExtraTreesRegressor",
    "model_type": "heating_dd_extratrees",
    "timestamp": "timestamp",
    "date_features": ["month", "day_of_week"]
    }

predict_heating_hours_extratrees:
  url: http://localhost:5003/action/regressor-model-predict
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
      "model_type": "heating_dd_extratrees",
      "mlr_predict_entity_id": "sensor.voorspelde_uren_extratrees",
      "mlr_predict_unit_of_measurement": "h",
      "mlr_predict_friendly_name": "Voorspelde uren extratrees",
      "new_values": [{{states("sensor.degree_day_prediction")}}, {{states("sensor.open_meteo_voorspelling_vandaag")}}, {{buiten_temp}}, {{binnen_temp}}, {{now().month}}, {{now().weekday()}}]
    }

# fit_heating_hours_mlpregressor:
#   url: http://localhost:5003/action/regressor-model-fit
#   method: POST
#   timeout: 300
#   content_type: "application/json"
#   payload: >-
#     {
#     "csv_file": "prediction.csv",
#     "features":["dd", "solar", "buiten_gisteren_mean", "beneden_gisteren_mean"],
#     "target": "hour",
#     "regression_model": "MLPRegressor",
#     "model_type": "heating_dd_mlpregressor",
#     "timestamp": "timestamp",
#     "date_features": ["month", "day_of_week"]
#     }

# predict_heating_hours_mlpregressor:
#   url: http://localhost:5003/action/regressor-model-predict
#   method: POST
#   timeout: 300
#   content_type: "application/json"
#   payload: >-
#     {
#       "model_type": "heating_dd_mlpregressor",
#       "mlr_predict_entity_id": "sensor.voorspelde_uren_mlpregressor",
#       "mlr_predict_unit_of_measurement": "h",
#       "mlr_predict_friendly_name": "Voorspelde uren mlpregressor",
#       "new_values": [{{states("sensor.degree_day_prediction")}}, {{states("sensor.open_meteo_voorspelling_vandaag")}}, {{buiten_temp}}, {{binnen_temp}}, {{now().month}}, {{now().weekday()}}]
#     }

fit_heating_hours_svr:
  url: http://localhost:5003/action/regressor-model-fit
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
    "csv_file": "prediction.csv",
    "features":["dd", "solar", "buiten_gisteren_mean", "beneden_gisteren_mean"],
    "target": "hour",
    "regression_model": "SVR",
    "model_type": "heating_dd_svr",
    "timestamp": "timestamp",
    "date_features": ["month", "day_of_week"]
    }

predict_heating_hours_svr:
  url: http://localhost:5003/action/regressor-model-predict
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
      "model_type": "heating_dd_svr",
      "mlr_predict_entity_id": "sensor.voorspelde_uren_svr",
      "mlr_predict_unit_of_measurement": "h",
      "mlr_predict_friendly_name": "Voorspelde uren svr",
      "new_values": [{{states("sensor.degree_day_prediction")}}, {{states("sensor.open_meteo_voorspelling_vandaag")}}, {{buiten_temp}}, {{binnen_temp}}, {{now().month}}, {{now().weekday()}}]
    }

fit_heating_hours_decisiontree:
  url: http://localhost:5003/action/regressor-model-fit
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
    "csv_file": "prediction.csv",
    "features":["dd", "solar", "buiten_gisteren_mean", "beneden_gisteren_mean"],
    "target": "hour",
    "regression_model": "DecisionTreeRegressor",
    "model_type": "heating_dd_decisiontree",
    "timestamp": "timestamp",
    "date_features": ["month", "day_of_week"]
    }

predict_heating_hours_decisiontree:
  url: http://localhost:5003/action/regressor-model-predict
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
      "model_type": "heating_dd_decisiontree",
      "mlr_predict_entity_id": "sensor.voorspelde_uren_decisiontree",
      "mlr_predict_unit_of_measurement": "h",
      "mlr_predict_friendly_name": "Voorspelde uren decisiontree",
      "new_values": [{{states("sensor.degree_day_prediction")}}, {{states("sensor.open_meteo_voorspelling_vandaag")}}, {{buiten_temp}}, {{binnen_temp}}, {{now().month}}, {{now().weekday()}}]
    }

fit_heating_hours_kneighbors:
  url: http://localhost:5003/action/regressor-model-fit
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
    "csv_file": "prediction.csv",
    "features":["dd", "solar", "buiten_gisteren_mean", "beneden_gisteren_mean"],
    "target": "hour",
    "regression_model": "KNeighborsRegressor",
    "model_type": "heating_dd_kneighbors",
    "timestamp": "timestamp",
    "date_features": ["month", "day_of_week"]
    }

predict_heating_hours_kneighbors:
  url: http://localhost:5003/action/regressor-model-predict
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
      "model_type": "heating_dd_kneighbors",
      "mlr_predict_entity_id": "sensor.voorspelde_uren_kneighbors",
      "mlr_predict_unit_of_measurement": "h",
      "mlr_predict_friendly_name": "Voorspelde uren kneighbors",
      "new_values": [{{states("sensor.degree_day_prediction")}}, {{states("sensor.open_meteo_voorspelling_vandaag")}}, {{buiten_temp}}, {{binnen_temp}}, {{now().month}}, {{now().weekday()}}]
    }

fit_heating_hours_elasticnet:
  url: http://localhost:5003/action/regressor-model-fit
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
    "csv_file": "prediction.csv",
    "features":["dd", "solar", "buiten_gisteren_mean", "beneden_gisteren_mean"],
    "target": "hour",
    "regression_model": "ElasticNet",
    "model_type": "heating_dd_elasticnet",
    "timestamp": "timestamp",
    "date_features": ["month", "day_of_week"]
    }

predict_heating_hours_elasticnet:
  url: http://localhost:5003/action/regressor-model-predict
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
      "model_type": "heating_dd_elasticnet",
      "mlr_predict_entity_id": "sensor.voorspelde_uren_elasticnet",
      "mlr_predict_unit_of_measurement": "h",
      "mlr_predict_friendly_name": "Voorspelde uren elasticnet",
      "new_values": [{{states("sensor.degree_day_prediction")}}, {{states("sensor.open_meteo_voorspelling_vandaag")}}, {{buiten_temp}}, {{binnen_temp}}, {{now().month}}, {{now().weekday()}}]
    }

fit_heating_hours_lasso:
  url: http://localhost:5003/action/regressor-model-fit
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
    "csv_file": "prediction.csv",
    "features":["dd", "solar", "buiten_gisteren_mean", "beneden_gisteren_mean"],
    "target": "hour",
    "regression_model": "LassoRegression",
    "model_type": "heating_dd_lasso",
    "timestamp": "timestamp",
    "date_features": ["month", "day_of_week"]
    }

predict_heating_hours_lasso:
  url: http://localhost:5003/action/regressor-model-predict
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
      "model_type": "heating_dd_lasso",
      "mlr_predict_entity_id": "sensor.voorspelde_uren_lasso",
      "mlr_predict_unit_of_measurement": "h",
      "mlr_predict_friendly_name": "Voorspelde uren lasso",
      "new_values": [{{states("sensor.degree_day_prediction")}}, {{states("sensor.open_meteo_voorspelling_vandaag")}}, {{buiten_temp}}, {{binnen_temp}}, {{now().month}}, {{now().weekday()}}]
    }

fit_heating_hours_ridge:
  url: http://localhost:5003/action/regressor-model-fit
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
    "csv_file": "prediction.csv",
    "features":["dd", "solar", "buiten_gisteren_mean", "beneden_gisteren_mean"],
    "target": "hour",
    "regression_model": "RidgeRegression",
    "model_type": "heating_dd_ridge",
    "timestamp": "timestamp",
    "date_features": ["month", "day_of_week"]
    }

predict_heating_hours_ridge:
  url: http://localhost:5003/action/regressor-model-predict
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
      "model_type": "heating_dd_ridge",
      "mlr_predict_entity_id": "sensor.voorspelde_uren_ridge",
      "mlr_predict_unit_of_measurement": "h",
      "mlr_predict_friendly_name": "Voorspelde uren ridge",
      "new_values": [{{states("sensor.degree_day_prediction")}}, {{states("sensor.open_meteo_voorspelling_vandaag")}}, {{buiten_temp}}, {{binnen_temp}}, {{now().month}}, {{now().weekday()}}]
    }

fit_heating_hours_linear:
  url: http://localhost:5003/action/regressor-model-fit
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
    "csv_file": "prediction.csv",
    "features":["dd", "solar", "buiten_gisteren_mean", "beneden_gisteren_mean"],
    "target": "hour",
    "regression_model": "LinearRegression",
    "model_type": "heating_dd_linear",
    "timestamp": "timestamp",
    "date_features": ["month", "day_of_week"]
    }

predict_heating_hours_linear:
  url: http://localhost:5003/action/regressor-model-predict
  method: POST
  timeout: 300
  content_type: "application/json"
  payload: >-
    {
      "model_type": "heating_dd_linear",
      "mlr_predict_entity_id": "sensor.voorspelde_uren_linear",
      "mlr_predict_unit_of_measurement": "h",
      "mlr_predict_friendly_name": "Voorspelde uren linear",
      "new_values": [{{states("sensor.degree_day_prediction")}}, {{states("sensor.open_meteo_voorspelling_vandaag")}}, {{buiten_temp}}, {{binnen_temp}}, {{now().month}}, {{now().weekday()}}]
    }