alias: "Alarm arm night"
id: 3ab59385-d409-4777-abae-9c461a9fd442
triggers:
  - trigger: state
    entity_id: media_player.philips_tv
    from: "on"
    to: "off"
  - trigger: state
    entity_id: light.slaapkamer_spot
    to: "off"
  - trigger: state
    entity_id: light.slaapkamer_hoog
    to: "off"
  - trigger: template
    value_template: >
      {{ states("binary_sensor.gphone_focus") == "on" and states("device_tracker.gphone_bermuda") == "home" }}
  - trigger: template
    value_template: >
      {{ states("binary_sensor.mphone_focus") == "on" and states("device_tracker.mphone_bermuda") == "home" }}
conditions:
  - condition: not
    conditions:
      - condition: state
        entity_id: media_player.mass_keuken
        state: "playing"
  - condition: and
    conditions:
      - condition: time
        after: "20:15:00"
        before: "04:00:00"
      - condition: template
        value_template: "{{ states('alarm_control_panel.ha_alarm') != 'arming' }}"
      - condition: template
        value_template: "{{ states('alarm_control_panel.ha_alarm') != 'armed_night' }}"
      - condition: template
        value_template: "{{ states('media_player.philips_tv') != 'on' }}"
      - condition: or
        conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: sensor.martine_status
                state: "Thuis"
              - condition: state
                entity_id: sensor.martine_status
                state: "Juist Aangekomen"
          - condition: or
            conditions:
              - condition: state
                entity_id: sensor.giel_status
                state: "Thuis"
              - condition: state
                entity_id: sensor.giel_status
                state: "Juist Aangekomen"
          - condition: or
            conditions:
              - condition: state
                entity_id: sensor.fien_status
                state: "Thuis"
              - condition: state
                entity_id: sensor.fien_status
                state: "Juist Aangekomen"
          - condition: or
            conditions:
              - condition: state
                entity_id: sensor.noor_status
                state: "Thuis"
              - condition: state
                entity_id: sensor.noor_status
                state: "Juist Aangekomen"
actions:
  - action: automation.turn_off
    entity_id: automation.welkom_allemaal_sonos_paused, automation.welkom_allemaal_sonos_playing, automation.welkom_sonos_paused, automation.welkom_sonos_playing

  - if:
      - condition: template
        value_template: >
          {{ is_state("binary_sensor.mphone_focus", "off") and is_state("binary_sensor.gphone_focus", "off") }}
    then:
      - action: light.turn_on
        data:
          brightness: 255
          rgb_color: [255, 236, 182]
          entity_id: light.slaapkamer_spot

  - delay:
      seconds: 5
  - action: alarm_control_panel.alarm_arm_night
    entity_id: alarm_control_panel.ha_alarm
    data:
      code: !secret alarm_code

  - delay:
      minutes: 20
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.badkamer_grouped_not_master
            state: "on"
        sequence:
          - action: media_player.unjoin
            target:
              entity_id: media_player.mass_badkamer
