alias: Light gang boven
id: eb69e93e-c561-46bb-8554-bf70d7e89099
description: ""
mode: restart
max_exceeded: silent
# variables:
#   no_motion_wait: 30
triggers:
  - trigger: state
    entity_id: binary_sensor.gang_boven_pir, light.gang_boven, binary_sensor.gang_boven_pir_2
    from: "off"
    to: "on"
    id: aan
  - trigger: time
    at: input_datetime.gang_boven_end_time
    id: uit
actions:
  - delay:
      milliseconds: 200
  - choose:
      - conditions:
          - condition: trigger
            id: aan
          - condition: or
            conditions:
              - condition: state
                entity_id: binary_sensor.gang_boven_bezetting
                state: "on"
              # - condition: state
              #   entity_id: binary_sensor.gang_hal_bezetting
              #   state: 'on'
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.giel_thuis_nacht
                state: "off"
              - condition: state
                entity_id: binary_sensor.martine_thuis_nacht
                state: "off"
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.gang_boven
          - action: input_datetime.set_datetime
            data:
              datetime: |
                {{ now() + timedelta(hours=1) }}
            target:
              entity_id: input_datetime.gang_boven_end_time
          - wait_for_trigger:
              - trigger: state
                entity_id: binary_sensor.gang_boven_bezetting
                from: "on"
                to: "off"
              # - trigger: state
              #   entity_id: binary_sensor.gang_hal_bezetting
              #   from: 'on'
              #   to: 'off'
          - action: input_datetime.set_datetime
            data:
              datetime: >
                {{ now() + timedelta(seconds=30) }}
            target:
              entity_id: input_datetime.gang_boven_end_time
      - conditions:
          - condition: trigger
            id: uit
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.gang_boven
    default:
      - action: input_datetime.set_datetime
        data:
          datetime: |
            {{ now() + timedelta(seconds=120) }}
        target:
          entity_id: input_datetime.gang_boven_end_time
