alias: Wled terug uit
id: 4d3f1b01-64fa-4c2b-ab81-9dfd2b3d2875
trigger:
  - platform: state
    entity_id: light.wled_fien
    to: "on"
    id: fien
  - platform: state
    entity_id: light.wled_noor
    to: "on"
    id: noor

actions:
  - choose:
    - conditions:
        - condition: trigger
          id: fien
      sequence:
        - action: input_button.press
          entity_id:
            - input_button.wled_fien_nightlight
    - conditions:
        - condition: trigger
          id: noor
      sequence:
        - action: input_button.press
          entity_id:
            - input_button.wled_noor_nightlight
