alias: Ledstrips terug uit
id: 7561b874-1b5c-4ea5-87d5-71494e234ea1
trigger:
  - platform: state
    entity_id: light.wled_fien
    from: "off"
    to: "on"
    id: fien
  - platform: state
    entity_id: light.wled_noor
    from: "off"
    to: "on"
    id: noor

actions:
  - choose:
    - conditions:
        - condition: trigger
          id: fien
      sequence:
        - action: input_button.press
          entity_id:
            - input_button.wled_fien_nightlight
    - conditions:
        - condition: trigger
          id: noor
      sequence:
        - action: input_button.press
          entity_id:
            - input_button.wled_noor_nightlight
