fit_heating_hours:
  sequence:
    # RandomForestRegressor
    - action: rest_command.fit_heating_hours
      data:
        regression_model: "RandomForestRegressor"
        model_type: heating_dd
    - delay:
        seconds: 4
    # GradientBoostingRegressor
    - action: rest_command.fit_heating_hours
      data:
        regression_model: "GradientBoostingRegressor"
        model_type: "heating_dd_gradientboosting"
    - delay:
        seconds: 4
    # AdaBoostRegressor
    - action: rest_command.fit_heating_hours
      data:
        regression_model: "AdaBoostRegressor"
        model_type: "heating_dd_adaboost"
    - delay:
        seconds: 4
    # ExtraTreesRegressor
    - action: rest_command.fit_heating_hours
      data:
        regression_model: "ExtraTreesRegressor"
        model_type: "heating_dd_extratrees"
    - delay:
        seconds: 4
    # SVR
    - action: rest_command.fit_heating_hours
      data:
        regression_model: "SVR"
        model_type: "heating_dd_svr"
    - delay:
        seconds: 4
    # DecisionTreeRegressor
    - action: rest_command.fit_heating_hours
      data:
        regression_model: "DecisionTreeRegressor"
        model_type: "heating_dd_decisiontree"
    - delay:
        seconds: 4
    # KNeighborsRegressor
    - action: rest_command.fit_heating_hours
      data:
    # KNeighborsRegressor
        regression_model: "KNeighborsRegressor"
        model_type: "heating_dd_kneighbors"
    - delay:
        seconds: 4
    # ElasticNet
    - action: rest_command.fit_heating_hours
      data:
        regression_model: "ElasticNet"
        model_type: "heating_dd_elasticnet"
    - delay:
        seconds: 4
    # LassoRegression
    - action: rest_command.fit_heating_hours
      data:
        regression_model: "LassoRegression"
        model_type: "heating_dd_lasso"
    - delay:
        seconds: 4
    # RidgeRegression
    - action: rest_command.fit_heating_hours
      data:
        regression_model: "RidgeRegression"
        model_type: "heating_dd_ridge"
    - delay:
        seconds: 4
    # LinearRegression
    - action: rest_command.fit_heating_hours
      data:
        regression_model: "LinearRegression"
        model_type: "heating_dd_linear"
    - delay:
        seconds: 4

