emhass_fit_test_models:
  alias: "EMHASS: Fit Models"
  sequence:
    
    # Test 2: LinearRegression
    - action: rest_command.forecast_model_fit_load_zonder_wp_test
      data:
        model_type: "load_forecast_linear"
        model: "LinearRegression"
    - delay:
        seconds: 5
    
    # Test 3: Ridge
    - action: rest_command.forecast_model_fit_load_zonder_wp_test
      data:
        model_type: "load_forecast_ridge"
        model: "RidgeRegression"
    - delay:
        seconds: 5
    
    # Test 4: Lasso
    - action: rest_command.forecast_model_fit_load_zonder_wp_test
      data:
        model_type: "load_forecast_lasso"
        model: "LassoRegression"

