fit_heating_hours:
  sequence:
    - service: recorder.get_statistics
      data:
        start_time: >-
          {{ (now().replace(hour=0, minute=0, second=0)- timedelta(hours =
          24)).isoformat() }}
        end_time: >-
          {{ (now().replace(hour=23, minute=0, second=0)- timedelta(hours =
          24)).isoformat() }}
        period: day
        statistic_ids:
          - sensor.benedentemperatuur_gefilterd
          - sensor.buiten_temperatuur
        types:
          - mean
      response_variable: temp_stats
    - action: rest_command.fit_heating_hours
    - delay:
        seconds: 14
    - action: rest_command.predict_heating_hours
      data:
        buiten_temp: >
          {{temp_stats.statistics["sensor.buiten_temperatuur"][0].mean | float(0) | round(2)}}
        binnen_temp: >
          {{temp_stats.statistics["sensor.benedentemperatuur_gefilterd"][0].mean | float(0) | round(2)}}
    - delay:
        seconds: 4
    - action: rest_command.fit_heating_hours_gradientboosting
    - delay:
        seconds: 14
    - action: rest_command.predict_heating_hours_gradientboosting
      data:
        buiten_temp: >
          {{temp_stats.statistics["sensor.buiten_temperatuur"][0].mean | float(0) | round(2)}}
        binnen_temp: >
          {{temp_stats.statistics["sensor.benedentemperatuur_gefilterd"][0].mean | float(0) | round(2)}}
    - delay:
        seconds: 4
    - action: rest_command.fit_heating_hours_adaboost
    - delay:
        seconds: 14
    - action: rest_command.predict_heating_hours_adaboost
      data:
        buiten_temp: >
          {{temp_stats.statistics["sensor.buiten_temperatuur"][0].mean | float(0) | round(2)}}
        binnen_temp: >
          {{temp_stats.statistics["sensor.benedentemperatuur_gefilterd"][0].mean | float(0) | round(2)}}
##########
    - delay:
        seconds: 4
    - action: rest_command.fit_heating_hours_extratrees
    - delay:
        seconds: 14
    - action: rest_command.predict_heating_hours_extratrees
      data:
        buiten_temp: >
          {{temp_stats.statistics["sensor.buiten_temperatuur"][0].mean | float(0) | round(2)}}
        binnen_temp: >
          {{temp_stats.statistics["sensor.benedentemperatuur_gefilterd"][0].mean | float(0) | round(2)}}
    - delay:
        seconds: 4

    - action: rest_command.fit_heating_hours_svr
    - delay:
        seconds: 14
    - action: rest_command.predict_heating_hours_svr
      data:
        buiten_temp: >
          {{temp_stats.statistics["sensor.buiten_temperatuur"][0].mean | float(0) | round(2)}}
        binnen_temp: >
          {{temp_stats.statistics["sensor.benedentemperatuur_gefilterd"][0].mean | float(0) | round(2)}}
    - delay:
        seconds: 4
    - action: rest_command.fit_heating_hours_decisiontree
    - delay:
        seconds: 14
    - action: rest_command.predict_heating_hours_decisiontree
      data:
        buiten_temp: >
          {{temp_stats.statistics["sensor.buiten_temperatuur"][0].mean | float(0) | round(2)}}
        binnen_temp: >
          {{temp_stats.statistics["sensor.benedentemperatuur_gefilterd"][0].mean | float(0) | round(2)}}
    - delay:
        seconds: 4
    - action: rest_command.fit_heating_hours_kneighbors
    - delay:
        seconds: 14
    - action: rest_command.predict_heating_hours_kneighbors
      data:
        buiten_temp: >
          {{temp_stats.statistics["sensor.buiten_temperatuur"][0].mean | float(0) | round(2)}}
        binnen_temp: >
          {{temp_stats.statistics["sensor.benedentemperatuur_gefilterd"][0].mean | float(0) | round(2)}}
    - delay:
        seconds: 4
    - action: rest_command.fit_heating_hours_elasticnet
    - delay:
        seconds: 14
    - action: rest_command.predict_heating_hours_elasticnet
      data:
        buiten_temp: >
          {{temp_stats.statistics["sensor.buiten_temperatuur"][0].mean | float(0) | round(2)}}
        binnen_temp: >
          {{temp_stats.statistics["sensor.benedentemperatuur_gefilterd"][0].mean | float(0) | round(2)}}
    - delay:
        seconds: 4
    - action: rest_command.fit_heating_hours_lasso
    - delay:
        seconds: 14
    - action: rest_command.predict_heating_hours_lasso
      data:
        buiten_temp: >
          {{temp_stats.statistics["sensor.buiten_temperatuur"][0].mean | float(0) | round(2)}}
        binnen_temp: >
          {{temp_stats.statistics["sensor.benedentemperatuur_gefilterd"][0].mean | float(0) | round(2)}}
    - delay:
        seconds: 4
    - action: rest_command.fit_heating_hours_ridge
    - delay:
        seconds: 14
    - action: rest_command.predict_heating_hours_ridge
      data:
        buiten_temp: >
          {{temp_stats.statistics["sensor.buiten_temperatuur"][0].mean | float(0) | round(2)}}
        binnen_temp: >
          {{temp_stats.statistics["sensor.benedentemperatuur_gefilterd"][0].mean | float(0) | round(2)}}
    - delay:
        seconds: 4
    - action: rest_command.fit_heating_hours_linear
    - delay:
        seconds: 14
    - action: rest_command.predict_heating_hours_linear
      data:
        buiten_temp: >
          {{temp_stats.statistics["sensor.buiten_temperatuur"][0].mean | float(0) | round(2)}}
        binnen_temp: >
          {{temp_stats.statistics["sensor.benedentemperatuur_gefilterd"][0].mean | float(0) | round(2)}}