emhass_publish_models:
  alias: EMHASS publish models
  mode: single
  sequence:
    # --- RIDGE ---
    - action: rest_command.publish_data
      data:
        prefix: "ridge_"
    - delay: "00:00:03"
    # --- LASSO ---
    - action: rest_command.publish_data
      data:
        prefix: "lasso_"
    - delay: "00:00:03"
    # # --- LINEAR ---
    - action: rest_command.publish_data
      data:
        prefix: "linear_"
    - delay: "00:00:01"
