from homeassistant.const import (
    DEVICE_CLASS_POWER,
    DEVICE_CLASS_CURRENT,
    DEVICE_CLASS_ENERGY,
    DEVICE_CLASS_POWER_FACTOR,
    DEVICE_CLASS_VOLTAGE,
    POWER_WATT,
    ELECTRIC_POTENTIAL_VOLT,
    ENERGY_KILO_WATT_HOUR,
    ELECTRIC_CURRENT_AMPERE,
    POWER_VOLT_AMPERE,
    FREQUENCY_HERTZ,
    TEMP_CELSIUS,
)

SOLAREDGE_SENSORS = {
    # "entry": [
    #     "Friendly name",
    #     "data type",
    #     "unit of measurement",
    #     1,
    #     "address",
    #     "count",
    #     "device class",
    #     "input type",
    #     "reverse",
    #     "scale",
    #     "offset",
    #     "precission",
    # ],
    "model_name": [
        "Model",
        "string",
        None,
        1,
        40020,
        16,
        None,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "serial_number": [
        "SN",
        "string",
        None,
        1,
        40052,
        16,
        None,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "model_id": [
        "Model ID",
        "uint",
        None,
        1,
        40068,
        1,
        None,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "grid_current": [
        "AC current",
        "uint",
        ELECTRIC_CURRENT_AMPERE,
        1,
        40071,
        1,
        DEVICE_CLASS_CURRENT,
        "holding",
        False,
        0.001,
        0,
        1,
    ],
    "phase_a_current": [
        "Phase A current",
        "uint",
        ELECTRIC_CURRENT_AMPERE,
        1,
        40072,
        1,
        None,
        "holding",
        False,
        0.001,
        0,
        1,
    ],
    "phase_b_current": [
        "Phase B current",
        "uint",
        ELECTRIC_CURRENT_AMPERE,
        1,
        40073,
        1,
        DEVICE_CLASS_CURRENT,
        "holding",
        False,
        0.001,
        0,
        1,
    ],
    "phase_c_current": [
        "Phase C current",
        "uint",
        ELECTRIC_CURRENT_AMPERE,
        1,
        40074,
        1,
        DEVICE_CLASS_CURRENT,
        "holding",
        False,
        0.001,
        0,
        1,
    ],
    "line_voltage_a_b": [
        "Voltage Phase AB",
        "uint",
        ELECTRIC_POTENTIAL_VOLT,
        1,
        40076,
        1,
        DEVICE_CLASS_VOLTAGE,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "line_voltage_b_c": [
        "Voltage Phase BC",
        "uint",
        ELECTRIC_POTENTIAL_VOLT,
        1,
        40077,
        1,
        DEVICE_CLASS_VOLTAGE,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "line_voltage_c_a": [
        "Voltage Phase CA",
        "uint",
        ELECTRIC_POTENTIAL_VOLT,
        1,
        40078,
        1,
        DEVICE_CLASS_VOLTAGE,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "phase_a_voltage": [
        "Phase A voltage",
        "uint",
        ELECTRIC_POTENTIAL_VOLT,
        1,
        40079,
        1,
        DEVICE_CLASS_VOLTAGE,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "phase_b_voltage": [
        "Phase B voltage",
        "uint",
        ELECTRIC_POTENTIAL_VOLT,
        1,
        40080,
        1,
        DEVICE_CLASS_VOLTAGE,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "phase_c_voltage": [
        "Phase C voltage",
        "uint",
        ELECTRIC_POTENTIAL_VOLT,
        1,
        40081,
        1,
        DEVICE_CLASS_VOLTAGE,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "active_power": [
        "Active power",
        "int",
        POWER_WATT,
        1,
        40083,
        1,
        DEVICE_CLASS_POWER,
        "holding",
        False,
        0.1,
        0,
        0,
    ],
    "grid_frequency": [
        "Grid frequency",
        "uint",
        FREQUENCY_HERTZ,
        1,
        40085,
        1,
        DEVICE_CLASS_POWER_FACTOR,
        "holding",
        False,
        0.01,
        0,
        0,
    ],
    "apparent_power": [
        "Apparent power",
        "int",
        POWER_VOLT_AMPERE,
        1,
        40087,
        1,
        DEVICE_CLASS_POWER,
        "holding",
        False,
        0.1,
        0,
        0,
    ],
    "reactive_power": [
        "Reactive power",
        "int",
        "VAr",
        1,
        40089,
        1,
        DEVICE_CLASS_POWER,
        "holding",
        False,
        0.01,
        0,
        0,
    ],
    "power_factor": [
        "Power factor",
        "int",
        None,
        1,
        40091,
        1,
        DEVICE_CLASS_POWER_FACTOR,
        "holding",
        False,
        0.01,
        0,
        0,
    ],
    "accumulated_yield_energy": [
        "Accumulated energy yield",
        "uint",
        ENERGY_KILO_WATT_HOUR,
        100,
        40093,
        2,
        DEVICE_CLASS_ENERGY,
        "holding",
        False,
        0.001,
        0,
        2,
    ],
    "dc_current": [
        "DC current",
        "uint",
        ELECTRIC_CURRENT_AMPERE,
        100,
        40096,
        1,
        DEVICE_CLASS_CURRENT,
        "holding",
        False,
        0.0001,
        0,
        1,
    ],
    "dc_voltage": [
        "DC voltage",
        "uint",
        ELECTRIC_POTENTIAL_VOLT,
        10,
        40098,
        1,
        DEVICE_CLASS_VOLTAGE,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "dc_input_power": [
        "DC input power",
        "int",
        POWER_WATT,
        1,
        40100,
        1,
        DEVICE_CLASS_POWER,
        "holding",
        False,
        0.1,
        0,
        0,
    ],
    "internal_temperature": [
        "Internal temperature",
        "int",
        TEMP_CELSIUS,
        10,
        40103,
        1,
        None,
        "holding",
        False,
        0.01,
        0,
        0,
    ],
    "device_status": [
        "Device status",
        "uint",
        None,
        1,
        40107,
        1,
        None,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "ac_current_scalefactor": [
        "AC current scalefactor",
        "int",
        "st",
        1,
        40075,
        1,
        None,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "ac_voltage_scalefactor": [
        "AC voltage scalefactor",
        "int",
        "st",
        1,
        40082,
        1,
        None,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "power_scalefactor": [
        "Power scalefactor",
        "int",
        "st",
        1,
        40084,
        1,
        None,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "frequency_scalefactor": [
        "Frequency scalefactor",
        "int",
        "st",
        1,
        40086,
        1,
        None,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "apparent_power_scalefactor": [
        "Apparent power scalefactor",
        "int",
        "st",
        1,
        40088,
        1,
        None,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "reactive_power_scalefactor": [
        "Reactive power scalefactor",
        "int",
        "st",
        1,
        40090,
        1,
        None,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "power_factor_scalefactor": [
        "Power factor scalefactor",
        "int",
        "st",
        1,
        40092,
        1,
        None,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "energy_scalefactor": [
        "Energy scalefactor",
        "int",
        "st",
        1,
        40095,
        1,
        None,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "dc_current_scalefactor": [
        "DC current scalefactor",
        "int",
        "st",
        1,
        40097,
        1,
        None,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "dc_voltage_scalefactor": [
        "DC voltage scalefactor",
        "int",
        "st",
        1,
        40099,
        1,
        None,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "dc_power_scalefactor": [
        "DC power scalefactor",
        "int",
        "st",
        1,
        40101,
        1,
        None,
        "holding",
        False,
        1,
        0,
        0,
    ],
    "heatsink_scalefactor": [
        "Heatsink scalefactor",
        "int",
        "st",
        1,
        40106,
        1,
        None,
        "holding",
        False,
        1,
        0,
        0,
    ],
}

SOLAREDGE_DEVICE_STATUSSES = {
    "1": "Off",
    "2": "Sleeping (auto-shutdown) – Night mode",
    "3": "Grid Monitoring/wake-up",
    "4": "Inverter is ON and producing power",
    "5": "Production (curtailed)",
    "6": "Shutting down",
    "7": "Fault",
    "8": "Maintenance/setup",
}
