- platform: trend
  sensors:
    badkamer_trend_up:
      friendly_name: "Badkamer Trend up"
      unique_id: 5f5debb6-91ec-43d5-9b87-43acc05b949a
      device_class: heat
      # max_samples: 6
      max_samples: 3
      entity_id: sensor.badkamer_luchtvochtigheid
      sample_duration: 600
      # min_gradient: 0.01666
      # sample_duration: 20
      min_gradient: 0.04

    badkamer_trend_down:
      friendly_name: "Badkamer Trend down"
      unique_id: 2eea3a9b-d740-4e29-a471-12f0befdc0a5
      device_class: cold
      # max_samples: 120
      entity_id: sensor.badkamer_luchtvochtigheid
      # sample_duration: 600
      # min_gradient: -0.01666
      max_samples: 2
      sample_duration: 300
      min_gradient: -0.03
