- platform: derivative
  name: "Beneden temperatuur slope"
  unique_id: cc51dfc5-f0b3-40c0-818c-0d40b40c1069
  source: sensor.benedentemperatuur_gefilterd
  unit_time: h
  unit: "°C/h"
  time_window: "00:10:00"