

# - platform: file
#   name: Solar csv_2
#   file_path: prediction.csv
#   value_template: '{{ value.split(",")[9] }}'
# - platform: file
#   name: Verwarming csv
#   file_path: prediction.csv
#   value_template: '{{ value.split(",")[10] }}'
#   unit_of_measurement: "°C"
# - platform: file
#   name: Verbruik csv
#   file_path: prediction.csv
#   value_template: '{{ value.split(",")[12] }}'
#   unit_of_measurement: "°C"
