- platform: integration
  source: sensor.warmtepomp_huidig_verbruik
  name: Warmtepomp kWh
  unique_id: 9fa67f04-8d56-41d6-93e9-052bf0a243ff
  method: left
  unit_prefix: k
  round: 3
  # shelly esphome

- platform: integration
  source: sensor.warmtepompboiler_huidig_verbruik
  name: Warmtepompboiler kWh
  unique_id: 9ad7ff6a-8e03-4731-8f14-4bcf530f99df
  method: left
  unit_prefix: k
  round: 3
  # shelly esphome

###  Toestellen  ###
- platform: integration
  source: sensor.verlichting_vermogen
  name: Verlichting kWh
  unique_id: bd96163c-a9b1-46ed-915f-ff6eb216971c
  method: left
  unit_prefix: k
  round: 3

- platform: integration
  # source: sensor.verluchting_vermogen
  source: sensor.dummy
  method: left
  name: Verluchting kWh
  unique_id: a83e5ac8-8153-4a97-af39-e995cadb1253
  unit_prefix: k
  round: 3

# - platform: integration
#   source: sensor.media_vermogen_2
#   method: left
#   name: Media kWh
#   unique_id: 4f8fcc4d-ded4-4ba8-b4d4-508a954dda54
#   unit_prefix: k
#   round: 3
- platform: integration
  # source: sensor.keuken_toestellen_2_vermogen
  source: sensor.dummy
  method: left
  name: Keuken toestellen 2 kWh
  unique_id: daa0974f-c2f0-437e-9ca8-e8f8fbfa2a1f
  unit_prefix: k
  round: 3
  # sensor.keuken_toestellen_2_verbruik

- platform: integration
  # source: sensor.koffiezet_vermogen
  source: sensor.dummy
  name: Koffiezet kWh
  unique_id: 40479fb2-765b-435e-80e5-16b91ed19b29
  method: left
  unit_prefix: k
  round: 3
  # sensor.koffiezet_verbruik

- platform: integration
  # source: sensor.regenwaterpomp_vermogen
  source: sensor.dummy
  name: Regenwaterpomp kWh
  unique_id: f3db719b-0716-4a4b-86b7-59c29eceb2da
  method: left
  unit_prefix: k
  round: 3
  # sensor.regenwaterpomp_verbruik

- platform: integration
  # source: sensor.afwasmachien_vermogen
  source: sensor.dummy
  name: Afwasmachien kWh
  unique_id: e9ba5f24-40b0-4e0a-97be-ae19c1fea464
  method: left
  unit_prefix: k
  round: 3
  # sensor.afwasmachien_verbruik

- platform: integration
  # source: sensor.wasmachien_vermogen
  source: sensor.dummy
  name: Wasmachien kWh
  unique_id: c29febe8-09ce-476a-9cb1-29595d7a08ac
  method: left
  unit_prefix: k
  round: 3
  # sensor.wasmachien_verbruik

- platform: integration
  # source: sensor.droogkast_vermogen
  source: sensor.dummy
  name: Droogkast kWh
  unique_id: df46b0fa-16d0-431c-b820-485c1299493d
  method: left
  unit_prefix: k
  round: 3
  # sensor.droogkast_verbruik

- platform: integration
  # source: sensor.keuken_ijskast_vermogen
  source: sensor.dummy
  name: Ijskast kWh
  unique_id: f9f851cf-4454-4814-8b25-af56d58918f4
  method: left
  unit_prefix: k
  round: 3
  # sensor.keuken_ijskast_verbruik

- platform: integration
  # source: sensor.keuken_oven_vermogen
  source: sensor.dummy
  name: Keuken oven kWh
  unique_id: 4eed2bb8-dd17-4f5c-92f4-c485ba578e33
  method: left
  unit_prefix: k
  round: 3
  # sensor.keuken_oven_verbruik

- platform: integration
  # source: sensor.keuken_microgolf_vermogen
  source: sensor.dummy
  name: Keuken microgolf kWh
  unique_id: 6a483ac2-7b4c-4727-973e-4c376d537bd2
  method: left
  unit_prefix: k
  round: 3
  # sensor.keuken_microgolf_verbruik

- platform: integration
  source: sensor.ventilator_kerstverlichting_vermogen
  name: Living Ventilator Kerstverlichting kWh
  unique_id: 227429cb-b46b-4dd9-8e7c-9f79f4e5b83b
  method: left
  unit_prefix: k
  round: 3
  # sensor.ventilator_kerstverlichting_verbruik

- platform: integration
  source: sensor.garage_ijskast_vermogen
  name: Ijskast garage kWh
  unique_id: 986356ba-5741-4b6a-ba95-53a55ee51d1b
  method: left
  unit_prefix: k
  round: 3
  # shelly esphome

- platform: integration
  source: sensor.garage_oplader_vermogen_2
  # source: sensor.dummy
  name: Garage oplader kWh
  unique_id: 3a85d571-c6ec-4511-a6b1-0c3e2d080ab3
  method: left
  unit_prefix: k
  round: 3
  # esphome

- platform: integration
  source: sensor.pries_onder_vermogen
  name: Pries onder kWh
  unique_id: c5eb36cd-1f27-4940-a7a4-4886177caa73
  method: left
  unit_prefix: k
  round: 3
  # shelly esphome

- platform: integration
  source: sensor.pries_boven_vermogen
  name: Pries boven kWh
  unique_id: 9f308ab9-8c03-4b9c-b41d-1727c09c37fb
  method: left
  unit_prefix: k
  round: 3
  # shelly esphome

- platform: integration
  source: sensor.pries_bureau_vermogen
  name: Pries bureau kWh
  unique_id: 02650751-ceca-494b-98e5-f2241b4e2596
  method: left
  unit_prefix: k
  round: 3
  # shelly esphome
