- id: '1603382266087'
  alias: profiler
  description: profiler
  trigger:
  - platform: time
    at: '17:59'
  condition: []
  actions:
  - action: profiler.start
    data: {}
  mode: single
- id: '1617444794333'
  alias: Shelly herstarten
  description: ''
  trigger:
  - platform: state
    entity_id: 'switch.shelly_badkamer_verluchting_herstarten '
    to: 'off'
    from: unavailable
  condition:
  - condition: state
    entity_id: binary_sensor.shelly_badkamer_verluchting_status
    state: 'off'
    for: 00:05:00
  actions:
  - action: switch.turn_on
    target:
      entity_id: switch.shelly_badkamer_verluchting_herstarten
  mode: parallel
  max: 10
- id: '1650959980916'
  alias: Unifi unavailable
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.droommachien
    from: home
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  actions:
  - action: notify.mobile_app_gphone
    data:
      message: Unifi nazien!!!
  mode: single
- id: '1675907714800'
  alias: Max piek notificatie 3
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '15'
  condition:
  - condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.input_number.max_peak_2.last_changed.timestamp()
      | timestamp_local()) < 900 }}

      '
  - condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states("sensor.uptime"))
      > 900 }}

      '
  actions:
  - action: persistent_notification.create
    data:
      message: "Op kwartierbasis:\n{% for state in states.sensor -%} {% if \"quarter\"
        in state.entity_id -%} {% if state.attributes.last_period | float(0) > 0
        -%}\n  {{ state.attributes.friendly_name }} = {{ state.attributes.last_period
        }} kWh\n{% endif -%} {% endif -%} {% endfor %}\nOp uurbasis:\n{% for state
        in states.sensor -%} {% if \"quarter\" in state.entity_id -%} {% if state.attributes.last_period
        | float(0) > 0 -%}\n  {{ state.attributes.friendly_name | replace(\"kwartierverbruik\",
        \"uurverbruik\") }} = {{ state.attributes.last_period | float * 4}} kWh\n{%
        endif -%} {% endif -%} {% endfor -%}"
  mode: single
- id: '1685887833753'
  alias: Beweging poort
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.poort
    to: 'on'
  condition: []
  actions:
  - action: notify.giel_en_martine
    data:
      message: Beweging poort
  mode: single
- id: '1699040529160'
  alias: poort gphone
  description: ''
  triggers:
  - entity_id:
    - binary_sensor.poort
    to: 'on'
    trigger: state
  conditions: []
  actions:
  - action: notify.mobile_app_gphone
    data:
      message: Poort
      data:
        actions:
        - action: POORT
          title: Afzetten?
  mode: single
- id: '1741689014825'
  alias: Gang verklikker
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.gang_boven_pir
    to: 'on'
    id: gang
  - trigger: state
    entity_id:
    - binary_sensor.trap_aqara_pir
    to: 'on'
    id: trap
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - gang
      sequence:
      - action: notify.mobile_app_gphone
        data:
          message: Gang boven!
          data:
            actions:
            - action: GANG
              title: Afzetten?
              uri: /lovelace/boven
    - conditions:
      - condition: trigger
        id:
        - trap
      sequence:
      - action: notify.mobile_app_gphone
        data:
          message: Trap!!!
          data: {}
      - action: automation.turn_off
        metadata: {}
        data:
          stop_actions: true
        target:
          entity_id: automation.gang_verklikker
  mode: parallel
  max: 10
