exclude:
  domains:
    - weblink
    - automation
    - updater
    - sun
    - group
  entities:
    - sensor.date
    - sensor.time
    - sensor.time_date
    - binary_sensor.buiten_fris_genoeg
    - zone.home
