# port: 8086
# database: !secret influxdb_db
# username: !secret influxdb_user
# password: !secret influxdb_password
max_retries: 3
default_measurement: state
# exclude:
#   entities:
#       - entity.id1
#       - entity.id2
#   domains:
#       - automation
# include:
#   entities:
#       - entity.id3
#       - entity.id4
# tags:
#   instance: prod
#   source: hass
