# port: 8086
# database: !secret influxdb_db
# username: !secret influxdb_user
# password: !secret influxdb_password
max_retries: 3
default_measurement: state
# exclude:
#   entities:
#       - entity.id1
#       - entity.id2
#   domains:
#       - automation
include:
  entities:
    - sensor.afwasmachien_kwh
    - sensor.afwasmachien_verbruik
    - sensor.afwasmachien_vermogen
    - sensor.all_standby_verbruik
    - sensor.badkamer_verwarming_verbruik
    - sensor.benedentemperatuur_gefilterd
    - sensor.branduren_warmtepomp
    - sensor.buiten_lichtsterkte
    - sensor.buiten_temperatuur
    - sensor.circulatie_verwarming_verbruik
    - sensor.droogkast_kwh
    - sensor.droogkast_verbruik
    - sensor.droogkast_vermogen
    - sensor.electricity_meter_energieproductie
    - sensor.electricity_meter_energieproductie_tarief_1
    - sensor.electricity_meter_energieproductie_tarief_1_compensation
    - sensor.electricity_meter_energieproductie_tarief_2
    - sensor.electricity_meter_energieproductie_tarief_2_compensation
    - sensor.electricity_meter_energieverbruik
    - sensor.electricity_meter_energieverbruik_tarief_1
    - sensor.electricity_meter_energieverbruik_tarief_1_cost
    - sensor.electricity_meter_energieverbruik_tarief_2
    - sensor.electricity_meter_energieverbruik_tarief_2_cost
    - sensor.electricity_meter_huidig_gemiddelde_vraag
    - sensor.electricity_meter_maximale_vraag_huidige_maand
    - sensor.emhass_afwasmachien
    - sensor.emhass_battery
    - sensor.emhass_droogkast
    - sensor.emhass_grid2
    - sensor.emhass_grid_lasso
    - sensor.emhass_grid_linear
    - sensor.emhass_grid_ridge
    - sensor.emhass_load
    - sensor.emhass_load_lasso
    - sensor.emhass_load_linear
    - sensor.emhass_load_ridge
    - sensor.emhass_pv
    - sensor.emhass_warmtepomp
    - sensor.emhass_warmtepompboiler
    - sensor.emhass_wasmachien
    - sensor.garage_computer_verbruik
    - sensor.garage_oplader_kwh
    - sensor.gas_meter_gasverbruik
    - sensor.gemiddelde_opbrengst_5m
    - sensor.gemiddelde_temp_beneden
    - sensor.gemiddelde_temp_binnen
    - sensor.gemiddelde_temp_boven
    - sensor.grid_consumption_kwh_old
    - sensor.grid_production_kwh_old
    - sensor.huawei_daily_energy_yield
    - sensor.huawei_energy
    - sensor.huidig_fluvius
    - sensor.huidig_verbruik
    - sensor.huidig_verbruik_zonder_wp
    - sensor.huidig_verbruik_zonder_wp_gefilterd
    - sensor.huidige_opbrengst
    - sensor.huidige_opbrengst_gefilterd
    - sensor.ijskast_garage_kwh
    - sensor.ijskast_kwh
    - sensor.kelder
    - sensor.keuken_ijskast_verbruik
    - sensor.keuken_luchtvochtigheid_2
    - sensor.keuken_microgolf_kwh
    - sensor.keuken_microgolf_verbruik
    - sensor.keuken_oven_kwh
    - sensor.keuken_oven_verbruik
    - sensor.keuken_toestellen_2_kwh
    - sensor.keuken_toestellen_2_verbruik
    - sensor.keuken_toestellen_3_verbruik
    - sensor.keuken_toestellen_verbruik
    - sensor.koffiezet_kwh
    - sensor.koffiezet_verbruik
    - sensor.living_media_verbruik
    - sensor.living_ventilator_kerstverlichting_kwh
    - sensor.media_verbruik
    - sensor.neerslag_zandhoven
    - sensor.nuc_verbruik
    - sensor.openweathermap_bewolking
    - sensor.people_home
    - sensor.poort_luchtvochtigheid
    - sensor.pries_boven_kwh
    - sensor.pries_bureau_kwh
    - sensor.pries_onder_kwh
    - sensor.pv_prediction_now
    - sensor.raspi_verbruik
    - sensor.regenwaterpomp_kwh
    - sensor.regenwaterpomp_verbruik
    - sensor.slaapkamer_fien_luchtvochtigheid_3
    - sensor.slaapkamer_fien_temperatuur_3
    - sensor.slaapkamer_fien_verwarming_verbruik
    - sensor.slaapkamer_luchtvochtigheid_3
    - sensor.slaapkamer_noor_luchtvochtigheid_3
    - sensor.slaapkamer_noor_temperatuur_3
    - sensor.slaapkamer_noor_verwarming_verbruik
    - sensor.slaapkamer_temperatuur_3
    - sensor.slaapkamer_verwarming_verbruik
    - sensor.solaredge_energy
    - sensor.solaredge_i1_ac_energy
    - sensor.thermostaat
    - sensor.total_battery_charge
    - sensor.total_battery_discharge
    - sensor.unifi_devices_verbruik
    - sensor.unifi_poe_verbruik_verbruik
    - sensor.unifi_verbruik
    - sensor.ventilator_kerstverlichting_verbruik
    - sensor.verlichting_kwh
    - sensor.verluchting_kwh
    - sensor.verluchting_verbruik_verbruik
    - sensor.vloer_vloertemperatuur
    - sensor.vloerverwarming_heen
    - sensor.vloerverwarming_terug
    - sensor.warm_water_extra_verbruik
    - sensor.warmtepomp_huidig_verbruik
    - sensor.warmtepomp_kwh
    - sensor.warmtepompboiler_huidig_verbruik
    - sensor.warmtepompboiler_kwh
    - sensor.wasmachien_kwh
    - sensor.wasmachien_verbruik
    - sensor.wasmachien_vermogen
    - sensor.water_meter_waterverbruik
    - sensor.water_meter_waterverbruik_cost
    - sensor.wc_verwarming_verbruik
    - sensor.emhass_cost
    - sensor.emhass_price
    - sensor.ecopower_afnameprijzen
    - sensor.ecopower_injectieprijzen
    - sensor.zolder_temperatuur
    - sensor.keuken_temperatuur
    - sensor.temp_living
    - sensor.living_temperatuur
    - sensor.temperatuur_living
    - sensor.temperatuur_slaapkamer
    - sensor.temperatuur_badkamer
    - sensor.battery_power
