purge_keep_days: 10
auto_purge: false
auto_repack: false
exclude:
  domains:
    - camera
    - group
    - scene
    - sun
    - weather
    - zone
    - update
    - image
    - tts
    - event
    - input_datetime
  entities:
    - sensor.unifi_vermogen
    - sensor.unifi_poe_vermogen
    - sensor.verlichting_vermogen
    - sensor.unifi_devices_vermogen
    - sensor.unifi_droommachien_vermogen
    - sensor.unifi_waskot_vermogen
    - sensor.unifi_media_vermogen
    - sensor.nuc_vermogen

    - sensor.date
    - sensor.date_time

    - sensor.time
    - sensor.time_date
    - sensor.last_boot

    - sensor.buiten_buiten_temperatuur
    - sensor.buiten_buiten_luchtdruk
    - sensor.badkamer_temperatuur
    - sensor.temperatuur_slaapkamer_2
    - sensor.temp_living_2

    - sensor.gft
    - sensor.papier
    - sensor.pmd
    - sensor.restafval
    - sensor.brewpi_verbruik
    - sensor.keukenpi_verbruik
    - sensor.livingpi_verbruik
    - sensor.prediction_horizon_span
    - button.roborock_a15_3b25_info
    - button.yeelink_monob_69dd_info
    - sensor.net_afname
    - sensor.net_terugsturen
    - sensor.neerslag_verwacht_zandhoven
    - binary_sensor.badkamer_trend_down
    - binary_sensor.badkamer_trend_up
    - sensor.energy_production_today_2
    - sensor.energy_production_today_3
    - sensor.energy_production_tomorrow_3
    - sensor.energy_production_tomorrow_2
    - sensor.energy_production_tomorrow
    ####  Emhass  ###
    - sensor.emhass_prod_price
    - sensor.ridge_emhass_prod_price
    - sensor.lasso_emhass_prod_price
    - sensor.linear_emhass_prod_price
    - sensor.emhass_load_forecast
    - sensor.ridge_emhass_load_forecast
    - sensor.lasso_emhass_load_forecast
    - sensor.linear_emhass_load_forecast
    - sensor.ridge_emhass_afwasmachien
    - sensor.lasso_emhass_afwasmachien
    - sensor.linear_emhass_afwasmachien
    - sensor.ridge_emhass_warmtepompboiler
    - sensor.lasso_emhass_warmtepompboiler
    - sensor.linear_emhass_warmtepompboiler
    - sensor.emhass_grid_forecast
    - sensor.ridge_emhass_grid_forecast
    - sensor.lasso_emhass_grid_forecast
    - sensor.linear_emhass_grid_forecast
    - sensor.ridge_emhass_wasmachien
    - sensor.lasso_emhass_wasmachien
    - sensor.linear_emhass_wasmachien
    - sensor.ridge_emhass_droogkast
    - sensor.lasso_emhass_droogkast
    - sensor.linear_emhass_droogkast
    - sensor.ridge_emhass_warmtepomp
    - sensor.lasso_emhass_warmtepomp
    - sensor.linear_emhass_warmtepomp
    - sensor.emhass_pv_forecast
    - sensor.ridge_emhass_pv_forecast
    - sensor.lasso_emhass_pv_forecast
    - sensor.linear_emhass_pv_forecast
    - sensor.emhass_load_cost
    - sensor.ridge_emhass_load_cost
    - sensor.lasso_emhass_load_cost
    - sensor.linear_emhass_load_cost
    - sensor.emhass_curtailment
    - sensor.ridge_emhass_curtailment
    - sensor.lasso_emhass_curtailment
    - sensor.linear_emhass_curtailment
    - sensor.p_batt_forecast
    - sensor.ridge_p_batt_forecast
    - sensor.lasso_p_batt_forecast
    - sensor.linear_p_batt_forecast
    - sensor.soc_batt_forecast
    - sensor.ridge_soc_batt_forecast
    - sensor.lasso_soc_batt_forecast
    - sensor.linear_soc_batt_forecast
    - sensor.nordpool_raw
    - sensor.optim_status
    - sensor.lasso_optim_status
    - sensor.p_batt_forecast
    - sensor.lasso_p_batt_forecast
    - sensor.p_deferrable0
    - sensor.lasso_p_deferrable0
    - sensor.p_deferrable1
    - sensor.lasso_p_deferrable1
    - sensor.p_deferrable2
    - sensor.lasso_p_deferrable2
    - sensor.p_deferrable3
    - sensor.lasso_p_deferrable3
    - sensor.p_deferrable4
    - sensor.lasso_p_deferrable4
    - sensor.p_grid_forecast
    - sensor.lasso_p_grid_forecast
    - sensor.p_load_forecast
    - sensor.lasso_p_load_forecast
    - sensor.p_pv_forecast
    - sensor.lasso_p_pv_forecast
    - sensor.ridge_optim_status
    - sensor.lasso_soc_batt_forecast
    - sensor.ridge_p_batt_forecast
    - sensor.lasso_total_cost_fun_value
    - sensor.ridge_p_deferrable0
    - sensor.lasso_unit_load_cost
    - sensor.ridge_p_deferrable1
    - sensor.lasso_unit_prod_price
    - sensor.ridge_p_deferrable2
    - sensor.linear_optim_status
    - sensor.ridge_p_deferrable3
    - sensor.linear_p_batt_forecast
    - sensor.ridge_p_deferrable4
    - sensor.linear_p_deferrable0
    - sensor.ridge_p_grid_forecast
    - sensor.linear_p_deferrable1
    - sensor.ridge_p_load_forecast
    - sensor.linear_p_deferrable2
    - sensor.ridge_p_pv_forecast
    - sensor.linear_p_deferrable3
    - sensor.ridge_soc_batt_forecast
    - sensor.linear_p_deferrable4
    - sensor.ridge_total_cost_fun_value
    - sensor.linear_p_grid_forecast
    - sensor.ridge_unit_load_cost
    - sensor.linear_p_load_forecast
    - sensor.ridge_unit_prod_price
    - sensor.linear_p_pv_forecast
    - sensor.soc_batt_forecast
    - sensor.linear_soc_batt_forecast
    - sensor.total_cost_fun_value
    - sensor.linear_total_cost_fun_value
    - sensor.unit_load_cost
    - sensor.linear_unit_load_cost
    - sensor.unit_prod_price
    - sensor.linear_unit_prod_price

  entity_globs:
    - sensor.*_poe_power
    - sensor.*_uptime
    - sensor.uptime*
    - sensor.cpu_*
    - sensor.swap_*
    - sensor.ram_*
    - sensor.wifi_*
    - sensor.shelly_*temperatuur
    - sensor.*_startuur
    - sensor.quarter_*
    - sensor.plant_*
    - sensor.*_cpu_utilization

  # event_types:
  #   - call_service # Don't record actions
