purge_keep_days: 365
auto_purge: false
auto_repack: false
exclude:
  domains:
    - camera
    - group
    - scene
    - sun
    - weather
    - zone
    - update
    - image
    - tts
    - event
    - input_datetime
  entities:
    - sensor.unifi_vermogen
    - sensor.unifi_poe_vermogen
    - sensor.verlichting_vermogen
    - sensor.unifi_devices_vermogen
    - sensor.unifi_droommachien_vermogen
    - sensor.unifi_waskot_vermogen
    - sensor.unifi_media_vermogen
    - sensor.nuc_vermogen
    - sensor.toestellen_vermogen
    - sensor.date
    - sensor.date_time
    # - sensor.notification_hour
    # - sensor.notification_minute
    # - sensor.notification_time
    # - sensor.notification_time_long
    - sensor.time
    - sensor.time_date
    - sensor.last_boot
    - sensor.buitentemperatuur_gefilterd
    - sensor.zonne_energie_gefilterd_lowpass
    - sensor.buiten_buiten_temperatuur
    - sensor.buiten_buiten_luchtdruk
    - sensor.badkamer_temperatuur
    - sensor.temperatuur_slaapkamer_2
    - sensor.temp_living_2
    # - sensor.purge_entites_1
    # - sensor.purge_entites_2
    - sensor.gft
    - sensor.papier
    - sensor.pmd
    - sensor.restafval
    - sensor.brewpi_verbruik
    - sensor.keukenpi_verbruik
    - sensor.livingpi_verbruik
    - sensor.prediction_horizon_span
    - button.roborock_a15_3b25_info
    - button.yeelink_monob_69dd_info
    - sensor.l1
    - sensor.l2
    - sensor.l3
    - sensor.net_afname
    - sensor.net_terugsturen
    - sensor.v1
    - sensor.v2
    - sensor.v3
    - sensor.neerslag_verwacht_zandhoven
    - sensor.average_electricity_price
    - binary_sensor.badkamer_trend_down
    - binary_sensor.badkamer_trend_up
    - sensor.energy_production_today_2
    - sensor.energy_production_today_3
    - sensor.energy_production_tomorrow_3
    - sensor.energy_production_tomorrow_2
    - sensor.energy_production_tomorrow
    - sensor.emhass_mpc
    - sensor.gemiddelde_opbrengst_5m

  entity_globs:
    - sensor.*_still_energy
    - sensor.*_move_energy
    - sensor.*_detection_distance
    - sensor.*_still_distance
    - sensor.*_moving_distance
    - sensor.*_poe_power
    - sensor.*_uptime
    - sensor.uptime*
    - sensor.cpu_*
    - sensor.swap_*
    - sensor.ram_*
    - sensor.wifi_*
    - sensor.shelly_*temperatuur
    - sensor.*_startuur
    - sensor.quarter_*
    - sensor.plant_*
    - sensor.*_cpu_utilization
    - sensor.*_memory_utilization
  
  # event_types:
  #   - call_service # Don't record actions
