ignored_entities:
  entities:
    - sensor.sonos_artist
    - cover.keuken_1
    - cover.keuken_2
    - cover.living
    - cover.slaapkamer
    - cover.slaapkamer_noor
    - cover.zonnetent
    - camera.tuin

    - switch.tuin_detect
    - switch.tuin_snapshots
    - light.wled_noor
    - sensor.wled_noor_estimated_current
    - switch.wled_noor_nightlight
    - switch.wled_noor_sync_receive
    - switch.wled_noor_sync_send
    - sensor.gphone_sim_2
    - binary_sensor.wled_firmware_2
    - number.wled_intensity_2
    - number.wled_speed_2
    - select.wled_live_override_2
    - sensor.frigate_events
    - sensor.wled_led_count_2
    - sensor.wled_max_current_2
    - switch.wled_reverse_2
    - binary_sensor.knop_giel_2_klik
    - binary_sensor.knop_giel_4_klik
    - binary_sensor.knop_giel_5_klik
    - binary_sensor.knop_martine_2_klik
    - binary_sensor.knop_martine_3_klik
    - binary_sensor.knop_martine_4_klik
    - binary_sensor.knop_noor_4_klik
    - sensor.lumi_lumi_plug_maeu01_0f91783c_device_temperature
    - sensor.lumi_lumi_plug_maeu01_7a8b783c_device_temperature
    - sensor.lumi_lumi_remote_b186acn01_36029102_device_temperature
    - sensor.lumi_lumi_sensor_motion_aq2_3a2ccf05_device_temperature
    - sensor.lumi_lumi_sensor_motion_aq2_64766906_device_temperature
    - sensor.lumi_lumi_sensor_motion_aq2_77275a06_device_temperature
    - sensor.lumi_lumi_sensor_smoke_e1495204_device_temperature

    - button.brouwerij_restart
    - button.brouwerij_shutdown
    - sensor.brouwerij_cpu_usage
    - sensor.brouwerij_memory_usage
    - sensor.buiten_buiten_lichtsterkte
    - sensor.buiten_buiten_luchtdruk
    - sensor.buiten_buiten_temperatuur
    - sensor.buiten_bssid
    - sensor.buiten_ip
    - sensor.buiten_ssid
    - sensor.living_ventilator_kerstverlichting_kwh
    - switch.buiten_herstarten
    - switch.buiten_weerstation_fan
    - media_player.mass_slaapkamer_noor
    - sensor.mass_slaapkamer_noor_vermogen

    - update.living_firmware
    - binary_sensor.living_status
    - binary_sensor.zithoek_presence
    - binary_sensor.danszaal_presence
    - sensor.living_temperatuur
    - sensor.living_luchtvochtigheid

    - sensor.zonnetent_vibratie_batterij
    - update.zonnetent_vibratie_firmware
    - sensor.home_alder_level
    - sensor.home_grasses_level
    - sensor.home_hazel_level
    - sensor.home_mugwort_level
    - sensor.home_ash_level
    - sensor.home_birch_level
    - sensor.home_oak_level
    - sensor.wled_fien_geschatte_stroom
    - sensor.wled_fien_max_stroom
    - sensor.wled_fien_verbruik
    - sensor.wled_fien_vermogen
    - sensor.wled_noor_geschatte_stroom
    - sensor.wled_noor_max_stroom
    - sensor.wled_noor_verbruik
    - sensor.wled_noor_vermogen
    # - binary_sensor.brewpi_online
    # - sensor.brewpi_verbruik
    # - sensor.brewpi_vermogen
    # - sensor.cpu_brewpi
    # - sensor.ram_brewpi
    # - sensor.swap_brewpi
    # - sensor.uptime_brewpi
    - button.brewpi_restart
    - button.brewpi_shutdown
    - sensor.brewpi_cpu_usage
    - sensor.brewpi_memory_usage
    - sensor.gphone_audio_output
    - update.brewpi_update
    - light.55oled806_12_ambilight
    - switch.55oled806_12_ambilight_hue
    - switch.55oled806_12_schermstatus

    ###  Robot  ###
    - button.robot_achteruit
    - button.robot_camera_go_down
    - button.robot_camera_go_left
    - button.robot_camera_go_right
    - button.robot_camera_go_stop
    - button.robot_camera_go_up
    - button.robot_camera_robot_camera_safe_mode_boot
    - button.robot_links
    - button.robot_preset_cruise
    - button.robot_preset_turbo
    - button.robot_preset_turtle
    - button.robot_rechts
    - button.robot_robot_safe_mode_boot
    - button.robot_stop
    - button.robot_vooruit
    - camera.robot_camera_robot
    - light.robot_camera_robot_laser
    - light.robot_camera_robot_light
    - number.robot_snelheid_algemeen
    - number.robot_snelheid_links
    - number.robot_snelheid_rechts
    - sensor.robot_camera_robot_camera_bssid
    - sensor.robot_camera_robot_camera_ip
    - sensor.robot_camera_robot_camera_ssid
    - sensor.robot_huidige_snelheid
    - sensor.robot_robot_bssid
    - sensor.robot_robot_ip
    - sensor.robot_robot_ssid
    - switch.robot_actieve_besturing
    - switch.robot_camera_robot_camera_herstarten
    - switch.robot_robot_herstarten
    - update.robot_firmware
