alias: "End times"
id: 85d4b37a-ed73-4a55-8b71-99e3cb74f7ec
mode: parallel
triggers:
  - trigger: time
    at: input_datetime.verluchting_end_time
    id: verluchting
  - trigger: time
    at: input_datetime.luchtdroger_end_time
    id: luchtdroger
  - trigger: time
    at: input_datetime.alle_tuinverlichting_end_time
    id: den_hof
  - trigger: time
    at: input_datetime.afdak_verlichting_end_time
    id: afdak
  - trigger: time
    at: input_datetime.keuken_end_time
    id: keuken
  - trigger: time
    at: input_datetime.slaapkamer_noor_verlichting_end_time
    id: noor
  - trigger: time
    at: input_datetime.slaapkamer_fien_verlichting_end_time
    id: fien
  - trigger: time
    at: input_datetime.wled_noor_end_time
    id: noorwled
  - trigger: time
    at: input_datetime.wled_fien_end_time
    id: fienwled
actions:
- choose:
  - conditions:
      - condition: trigger
        id: verluchting
    sequence:
      - action: switch.turn_off
        entity_id: switch.badkamer_verluchting
      - action: switch.turn_off
        entity_id: switch.zolder_verluchting
      - condition: template
        value_template: >
          {% set keuken = states("sensor.condensatie_marge_keuken") | float (0) -%}
          {% set slaapkamer = states("sensor.condensatie_marge_slaapkamer") | float (0) -%}
          {% set noor = states("sensor.condensatie_marge_noor") | float (0) -%}
          {% set fien = states("sensor.condensatie_marge_fien") | float (0) -%}
          {{ [keuken, slaapkamer, noor, fien] | min > 3 }}
      - action: switch.turn_off
        entity_id: switch.verluchting
  - conditions:
      - condition: trigger
        id: luchtdroger
      - condition: template
        value_template: >
          {% set keuken = states("sensor.condensatie_marge_keuken") | float (0) -%}
          {% set slaapkamer = states("sensor.condensatie_marge_slaapkamer") | float (0) -%}
          {% set noor = states("sensor.condensatie_marge_noor") | float (0) -%}
          {% set fien = states("sensor.condensatie_marge_fien") | float (0) -%}
          {{ [keuken, slaapkamer, noor, fien] | min > 3 }}
    sequence:
      - action: switch.turn_off
        entity_id: switch.luchtdroger
  - conditions:
      - condition: trigger
        id: den_hof
    sequence:
      - action: light.turn_off
        target:
          entity_id: light.alle_tuinverlichting
  - conditions:
      - condition: trigger
        id: afdak
    sequence:
      - action: light.turn_off
        target:
          entity_id: light.afdak_verlichting
  - conditions:
      - condition: trigger
        id: keuken
    sequence:
      - action: light.turn_off
        target:
          entity_id:
            - light.keuken_inkom
            - light.keuken_luster
            - light.keuken_spots
  - conditions:
      - condition: trigger
        id: noor
    sequence:
      - action: light.turn_off
        target:
          entity_id: light.noor
  - conditions:
      - condition: trigger
        id: fien
    sequence:
      - action: light.turn_off
        target:
          entity_id: light.fien
  - conditions:
      - condition: trigger
        id: noorwled
    sequence:
      - action: light.turn_off
        target:
          entity_id: light.wled_noor
  - conditions:
      - condition: trigger
        id: fienwled
    sequence:
      - action: light.turn_off
        target:
          entity_id: light.wled_fien