alias: "Heating csv"
id: 157b1d57-73d9-4f39-82c6-13ce0cf4288a
triggers:
  - trigger: time
    at: "23:59:32"
actions:
  - action: recorder.get_statistics
    data:
      start_time: "{{ now().replace(hour=0, minute=0, second=0).isoformat() }}"
      end_time: "{{ now().isoformat() }}"
      period: day
      types:
        - change
      statistic_ids:
        - sensor.huawei_energy
        - sensor.solaredge_energy
    response_variable: solar_stats

  - action: recorder.get_statistics
    data:
      start_time: >-
        {{ (now().replace(hour=0, minute=0, second=0)- timedelta(hours =
        24)).isoformat() }}
      end_time: >-
        {{ (now().replace(hour=23, minute=0, second=0)- timedelta(hours =
        24)).isoformat() }}
      period: day
      statistic_ids:
        - sensor.benedentemperatuur_gefilterd
        - sensor.buiten_temperatuur
      types:
        - mean
    response_variable: temp_stats

  - action: notify.send_message
    target:
      entity_id: notify.prediction
    data:
      message: >
        {% set solaredge = solar_stats.statistics["sensor.solaredge_energy"][-1].change | float(0) -%}
        {% set huawei = solar_stats.statistics["sensor.huawei_energy"][-1].change | float(0) -%}
        {% set buiten_gisteren_mean = temp_stats.statistics["sensor.buiten_temperatuur"][0].mean | float(0) | round(2) -%}
        {% set beneden_gisteren_mean = temp_stats.statistics["sensor.benedentemperatuur_gefilterd"][0].mean | float(0) | round(2) -%}

        {% set dd = states('sensor.degree_day_daily') |float -%}
        {% set hour = states('sensor.branduren_warmtepomp_vandaag') |float | round(2) -%}
        {% set solar = (solaredge + huawei) | round(3) -%}
        {% set time = now() -%}
        {% set max_setpoint = 21 -%}

          {{time}},{{dd}},{{solar}},{{hour}},{{buiten_gisteren_mean}},{{beneden_gisteren_mean}},{{max_setpoint}}

  - action: notify.send_message
    target:
      entity_id: notify.prediction_share
    data:
      message: >
        {% set solaredge = solar_stats.statistics["sensor.solaredge_energy"][-1].change | float(0) -%}
        {% set huawei = solar_stats.statistics["sensor.huawei_energy"][-1].change | float(0) -%}
        {% set buiten_gisteren_mean = temp_stats.statistics["sensor.buiten_temperatuur"][0].mean | float(0) | round(2) -%}
        {% set beneden_gisteren_mean = temp_stats.statistics["sensor.benedentemperatuur_gefilterd"][0].mean | float(0) | round(2) -%}

        {% set dd = states('sensor.degree_day_daily') |float -%}
        {% set hour = states('sensor.branduren_warmtepomp_vandaag') |float | round(2) -%}
        {% set solar = (solaredge + huawei) | round(3) -%}
        {% set time = now() -%}
        {% set max_setpoint = 21 -%}

          {{time}},{{dd}},{{solar}},{{hour}},{{buiten_gisteren_mean}},{{beneden_gisteren_mean}},{{max_setpoint}}

  # - action: notify.send_message
  #   target:
  #     entity_id: notify.file
  #   data:
  #     message: >
  #       {% set solaredge = solar_stats.statistics["sensor.solaredge_energy"][-1].change | float(0) -%}
  #       {% set huawei = solar_stats.statistics["sensor.huawei_energy"][-1].change | float(0) -%}
  #       {% set buiten_gisteren_mean = temp_stats.statistics["sensor.buiten_temperatuur"][0].mean | float(0) | round(2) -%}
  #       {% set beneden_gisteren_mean = temp_stats.statistics["sensor.benedentemperatuur_gefilterd"][0].mean | float(0) | round(2) -%}

  #       {% set dd = states('sensor.degree_day_daily') |float -%}
  #       {% set hour = states('sensor.branduren_warmtepomp_vandaag') |float | round(2) -%}
  #       {% set solar = (solaredge + huawei) | round(3) -%}
  #       {% set time = now() -%}
  #       {% set max_setpoint = 21 -%}

  #         {{time}},{{dd}},{{solar}},{{hour}},{{buiten_gisteren_mean}},{{beneden_gisteren_mean}},{{max_setpoint}}
