alias: "Oplader electrische fiets aan/uit"
id: c8dc7693-df59-44e3-8a60-b6d7160c5c3f
triggers:
  - trigger: time
    at: "14:02:00"
  - trigger: state
    entity_id: input_select.noor_status_dropdown
    to: 'Juist Aangekomen'
    for:
      minutes: 2
    id: noor_status
  - trigger: state
    entity_id: input_select.fien_status_dropdown
    to: 'Juist Aangekomen'
    for:
      minutes: 2
    id: fien_status
  - trigger: state
    entity_id: alarm_control_panel.ha_alarm
    id: armed_night
    to: "armed_night"
    for:
      minutes: 210
  - trigger: numeric_state
    entity_id: sensor.garage_oplader_vermogen
    id: garage_oplader
    above: 1
    below: 10
    for:
      minutes: 60
  - trigger: numeric_state
    entity_id: sensor.pries_boven_vermogen
    id: pries_boven
    above: 1
    below: 10
    for:
      minutes: 60
  - trigger: numeric_state
    entity_id: sensor.pries_onder_vermogen
    id: pries_onder
    above: 1
    below: 10
    for:
      minutes: 60
conditions:
  condition: and
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
actions:
  - choose:
    - conditions:
        - condition: trigger
          id: noor_status
      sequence:
        - action: switch.turn_on
          target:
            entity_id: switch.pries_boven, switch.pries_onder
    - conditions:
        - condition: trigger
          id: fien_status
      sequence:
        - action: switch.turn_on
          target:
            entity_id: switch.pries_boven, switch.pries_onder
    - conditions:
        - condition: template
          value_template: >
            {{ now().hour == 14 }}
      sequence:
        - action: switch.turn_on
          target:
            entity_id: switch.garage_oplader, switch.pries_boven, switch.pries_onder
    - conditions:
        - condition: trigger
          id: garage_oplader
      sequence:
        - action: switch.turn_off
          target:
            entity_id: switch.garage_oplader
    - conditions:
        - condition: trigger
          id: pries_boven
      sequence:
        - action: switch.turn_off
          target:
            entity_id: switch.pries_boven
    - conditions:
        - condition: trigger
          id: pries_onder
      sequence:
        - action: switch.turn_off
          target:
            entity_id: switch.pries_onder
    - conditions:
        - condition: trigger
          id: armed_night
      sequence:
        - action: switch.turn_off
          target:
            entity_id: switch.garage_oplader, switch.pries_boven, switch.pries_onder
  # - action: >
  #     {% if now().hour == 16 %}
  #       switch.turn_on
  #     {% else %}
  #       switch.turn_off
  #     {% endif %}
  #   entity_id: switch.garage_oplader
