get_forecast:
  name: Get Solar Forecast
  description: Get current solar forecast

  fields:
    entry_id:
      description: Config entry to get forecast from. Go to Settings->Integrations->Machine Learning Solar Forecast -> 3-dots-menu -> Copy ID to find it
      required: true
      selector:
        text:

    start:
      description: Start timestamp
      example: "2026-03-01T00:00:00Z"
      required: false
      selector:
        datetime: {}

    end:
      description: End timestamp
      example: "2026-03-15T00:00:00Z"
      required: false
      selector:
        datetime: {}