alarm_sound:
  sequence:
    - action: media_player.play_media
      continue_on_error: true
      target:
        entity_id:
          - media_player.mass_keuken
          - media_player.mass_2c
          - media_player.mass_move
          - media_player.mass_living_2
      data:
        announce: true
        media_content_type: music
        extra:
          volume: 65
        media_content_id: http://192.168.79.54:8123/local/sounds/Countdown.mp3
    # - action: music_assistant.play_announcement
    #   data:
    #     url: http://192.168.79.54:8123/local/sounds/Countdown.mp3
    #     announce_volume: 60
    #   target:
    #     entity_id: media_player.sonos
    - delay: "00:00:05"
    - action: media_player.play_media
      continue_on_error: true
      target:
        entity_id:
          - media_player.mass_keuken
          - media_player.mass_2c
          - media_player.mass_move
          - media_player.mass_living_2
      data:
        announce: true
        media_content_type: music
        extra:
          volume: 65
        media_content_id: http://192.168.79.54:8123/local/sounds/Siren_Noise.mp3
    # - action: music_assistant.play_announcement
    #   data:
    #     url: http://192.168.79.54:8123/local/sounds/Siren_Noise.mp3
    #     announce_volume: 60
    #   target:
    #     entity_id: media_player.sonos
    - delay: "00:00:05"
    - action: media_player.play_media
      continue_on_error: true
      target:
        entity_id:
          - media_player.mass_keuken
          - media_player.mass_2c
          - media_player.mass_move
          - media_player.mass_living_2
      data:
        announce: true
        media_content_type: music
        extra:
          volume: 65
        media_content_id: http://192.168.79.54:8123/local/sounds/Siren_Noise.mp3
    - delay: "00:00:05"
    - action: media_player.play_media
      continue_on_error: true
      target:
        entity_id:
          - media_player.mass_keuken
          - media_player.mass_2c
          - media_player.mass_move
          - media_player.mass_living_2
      data:
        announce: true
        media_content_type: music
        extra:
          volume: 65
        media_content_id: http://192.168.79.54:8123/local/sounds/Siren_Noise.mp3
    - delay: "00:00:05"
    - action: media_player.play_media
      continue_on_error: true
      target:
        entity_id:
          - media_player.mass_keuken
          - media_player.mass_2c
          - media_player.mass_move
          - media_player.mass_living_2
      data:
        announce: true
        media_content_type: music
        extra:
          volume: 65
        media_content_id: http://192.168.79.54:8123/local/sounds/Siren_Noise.mp3
    - delay: "00:00:05"
    - action: media_player.play_media
      continue_on_error: true
      target:
        entity_id:
          - media_player.mass_keuken
          - media_player.mass_2c
          - media_player.mass_move
          - media_player.mass_living_2
      data:
        announce: true
        media_content_type: music
        extra:
          volume: 65
        media_content_id: http://192.168.79.54:8123/local/sounds/Siren_Noise.mp3

