alias: Event trigger
id: 8a1860bd-de9f-4340-a55a-67fae6fb80c0
description: ""
triggers:
  - trigger: event
    event_type: "logbook_entry"
    id: frigate
    # optional
    event_data:
      name: custom-sidebar
      message: "sidebar_item_clicked: Frigate"
      domain: person
      entity_id: person.martine
    # context:
    #   user_id:
    #   # any of these will match
    #     - "MY_USER_ID"
    #     - "ANOTHER_USER_ID"
  - trigger: event
    event_type: "logbook_entry"
    id: camera
    # optional
    event_data:
      name: custom-sidebar
      message: "panel_visited: /lovelace/camera?external_auth=1"
      domain: person
      entity_id: person.martine
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: frigate
        sequence:
          - action: notify.mobile_app_gphone
            data:
              title: Frigate
              message: >
                Er wordt gekeken.
      - conditions:
          - condition: trigger
            id: camera
        sequence:
          - action: notify.mobile_app_gphone
            data:
              title: Camera
              message: >
                Er wordt gekeken.
