alias: Reload integrations
description: "Herladen van integraties bij unkown of unavailable."
id: 57abe3da-cb31-43f9-bea8-a3d73f4d3b5c
mode: parallel
triggers:
  - trigger: template
    value_template: >
      {{ states("climate.living")  is in ["unavailable", "unknown"]}}
    for:
      minutes: 2
    id: netatmo
  - trigger: template
    value_template: >
      {{ states("sensor.huawei_active_power")  is in ["unavailable", "unknown"]}}
    for:
      minutes: 2
    id: huawei
  - trigger: template
    value_template: >
      {{ states("sensor.energy_production_today")  is in ["unavailable", "unknown"]}}
    for:
      minutes: 2
    id: open_meteo
  - trigger: template
    value_template: >
      {{ states("sensor.energy_production_tomorrow")  is in ["unavailable", "unknown"]}}
    for:
      minutes: 2
    id: open_meteo
  - trigger: template
    value_template: >
      {{ states("sensor.energy_production_today_2")  is in ["unavailable", "unknown"]}}
    for:
      minutes: 2
    id: open_meteo_2
  - trigger: template
    value_template: >
      {{ states("sensor.energy_production_tomorrow_2")  is in ["unavailable", "unknown"]}}
    for:
      minutes: 2
    id: open_meteo_2
  - trigger: template
    value_template: >
      {{ states("sensor.energy_production_today_3")  is in ["unavailable", "unknown"]}}
    for:
      minutes: 2
    id: open_meteo_3
  - trigger: template
    value_template: >
      {{ states("sensor.energy_production_tomorrow_3")  is in ["unavailable", "unknown"]}}
    for:
      minutes: 2
    id: open_meteo_3
  
  - trigger: template
    value_template: >
      {{ states("vacuum.claptrap")  is in ["unavailable", "unknown"]}}
    for:
      minutes: 2
    id: claptrap
  - trigger: template
    value_template: >
      {{ states("sensor.electricity_meter_actief_tarief")  is in ["unavailable", "unknown"]}}
    for:
      minutes: 3
    id: dsmr
  - trigger: template
    value_template: >
      {{ states("camera.tuin")  is in ["unavailable", "unknown"]}}
    for:
      minutes: 2
    id: camera_tuin
actions:
  - choose:
    - conditions:
        - condition: trigger
          id: huawei
      sequence:
        - action: homeassistant.reload_config_entry
          target:
            entity_id: sensor.huawei_active_power
          data:
            entry_id: >
              {{ config_entry_id('sensor.huawei_active_power') }}
    - conditions:
        - condition: trigger
          id: open_meteo
      sequence:
        - action: homeassistant.reload_config_entry
          target:
            entity_id: sensor.energy_production_tomorrow
          data: 
            entry_id: >
              {{ config_entry_id('sensor.energy_production_tomorrow') }}
    - conditions:
        - condition: trigger
          id: open_meteo_2
      sequence:
        - action: homeassistant.reload_config_entry
          target:
            entity_id: sensor.energy_production_tomorrow_2
          data:
            entry_id: >
              {{ config_entry_id('sensor.energy_production_tomorrow_2') }}
    - conditions:
        - condition: trigger
          id: netatmo
      sequence:
        - action: homeassistant.reload_config_entry
          target:
            entity_id: climate.living
          data:
            entry_id: >
              {{ config_entry_id('climate.living') }}
    - conditions:
        - condition: trigger
          id: open_meteo_3
      sequence:
        - action: homeassistant.reload_config_entry
          target:
            entity_id: sensor.energy_production_tomorrow_3
          data:
            entry_id: >
              {{ config_entry_id('sensor.energy_production_tomorrow_3') }}
    
    - conditions:
        - condition: trigger
          id: claptrap
      sequence:
        - action: notify.mobile_app_gphone
          data:
            message: Claptrap reload
        - action: unifi.reconnect_client
          data:
            device_id: 898240675928a9586b500febb0f72316
        - delay:
            minutes: 2
        - action: homeassistant.reload_config_entry
          data:
            entry_id: |
              {{ config_entry_id('vacuum.claptrap') }}
          target:
            entity_id: vacuum.claptrap
    
    - conditions:
        - condition: trigger
          id: camera_tuin
      sequence:
        - action: notify.mobile_app_gphone
          data:
            message: Camera tuin reload
        - action: button.press
          target:
            entity_id: button.usw_lite_8_dahua_power_cycle
        

    - conditions:
        - condition: trigger
          id: dsmr
      sequence:
        - action: notify.mobile_app_gphone
          data:
            message: DSMR reload
        - action: homeassistant.reload_config_entry
          data:
            entry_id: |
              {{ config_entry_id('sensor.electricity_meter_actief_tarief') }}
          target:
            entity_id: sensor.electricity_meter_actief_tarief