alias: Schuifke
id: f5b872a7-e61d-4a78-ae81-30ab1817511a
description: ""
triggers:
  - trigger: state
    entity_id: binary_sensor.bthome_sensor_969c_window
    to: "on"
actions:
  - choose:
    - conditions:
        - condition: not
          conditions:
            - condition: state
              entity_id: sensor.gphone_area
              state: "Garage"
      sequence:
        - action: notify.mobile_app_gphone
          data:
            title: Wie zit er aan het schuifke? 
            message: >
              {% set verdachten = ["sensor.mphone_area", "sensor.fphone_area", "sensor.nphone_area"] %}
              {% set schuldige = namespace(all=[]) %}
              {% for verdachte in verdachten %}
                {% if states(verdachte) == "Garage" %}
                  {% set schuldige.all = schuldige.all + [state_attr(verdachte, 'friendly_name').split(" ")[0]] %}
                {% endif %}
              {% endfor %}
              De verdachten zijn: {{ schuldige.all| join(" of ") }}.
            