- sensor:
    - name: "Afwasmachien uren"
      unique_id: 062928fa-46a0-407c-9947-085b5278ec96
      unit_of_measurement: "uur"
      state: >
        {% if states("input_boolean.afwasmachien_starten") == 'on' -%}
          {% if states("switch.afwasmachien") == 'off' -%}
            2.5
          {% elif states("input_boolean.emhass_afwasmachien") == 'on' -%}
            {% if (2.5 - ((as_timestamp(now()) - states("sensor.afwasmachien_is_gestart_op") | float(0)) / 3600) | round(1)) | float(0) > 0  -%}
              {{ 2.5 - ((as_timestamp(now()) - states("sensor.afwasmachien_is_gestart_op") | float(0)) / 3600) | round(1) }}
            {% else -%}
              0
            {% endif -%}
          {% else -%}
            0
          {% endif -%}
        {% else -%}
          0
        {% endif -%}
    
    - name: Afwasmachien startuur
      unique_id: c38353a5-d1d8-4f10-a826-dbb2cf432c07
      state: >
        {% from 'easy_time.jinja' import easy_relative_time -%}
        {% set best_model = states('sensor.best_emhass_model_load_7d') | lower -%}
        {% set load = (state_attr('sensor.' + best_model + '_p_deferrable2', 'deferrables_schedule')
                |map(attribute=best_model + '_p_deferrable2')
                |list) -%}
        {% set time = (state_attr('sensor.' + best_model + '_p_deferrable2', 'deferrables_schedule')
                |map(attribute='date')
                |list) -%}
        {% if is_state("input_boolean.emhass_afwasmachien", "on") -%}
          Staat op
        {% else -%}
          {% set new_list = namespace(all=[]) -%}
            {% for i in range (load | length) -%}
              {% if load[i] | float(0) > 1 -%}
                {{ (easy_relative_time(time [i], max_period='minute', language='nl')) }}
                {% break -%}
              {% endif -%}
            {% endfor -%}
          {% endif -%}
      availability: >-
        {{ states('sensor.best_emhass_model_load_7d') not in ('unknown', 'unavailable', 'None') }}
    
    - name: Afwasmachien end timesteps
      unique_id: 32c63c15-0e67-4686-8680-1a8ca97f4aff
      unit_of_measurement: 5m
      state: >
        {% set steps = (((states("input_datetime.emhass_afwasmachien_end_time") | as_timestamp) - now() | as_timestamp) / 300) -%}
        {% set hours_to_operate = states("sensor.afwasmachien_uren") | float(0) -%}
        {% set op_blocks = (hours_to_operate * 12) | round(0, 'ceil') -%}
        {% if is_state("input_boolean.afwasmachien_starten", "on") -%}
          {% if is_state('input_boolean.emhass_afwasmachien', "on") -%}
            {{ op_blocks }}
          {% else -%}
            {{ max(op_blocks, steps|int, 0) }}
          {% endif -%} 
        {% else -%}
          0
        {% endif -%}