- sensor:
    - name: "Ecopower Afnameprijzen"
      unique_id: 16ccc75e-d8ab-4b79-ad3a-af3d289b1724
      unit_of_measurement: "EUR/kWh"
      state: >
        {% set factor_A = 1.02 -%}
        {% set factor_B = 0.004 -%}
        {% set GSC = 0.011 -%}
        {% set WKC = 0.00392 -%}
        {% set nettarief = 0.0505027 -%}
        {% set heffing = 0.0019261 -%}
        {% set accijns = 0.04748 -%}
        {% set VAT_scaling = 1.06 -%}
        {% set quarter_index = (now().minute // 5) -%}
        {% set current_hour = now().hour -%}
        {% set current_time_index = current_hour * 12 + quarter_index -%}
        {% set today_prices_data = (state_attr("sensor.nordpool_raw", "raw_today_prices") | map(attribute='price') |list ) -%}
        {% set tomorrow_prices_data = state_attr("sensor.nordpool_raw", "raw_tomorrow_prices") | map(attribute='price') |list -%}

        {% set all_prices = today_prices_data + tomorrow_prices_data  -%}
        {% set ns = namespace(result=[]) -%}
        {% for price in all_prices -%}
          {% set adjusted_price = 0 if (price | float | abs) < 0.12 else price -%}
          {% set ns.result = ns.result + [adjusted_price] * 3 -%}
        {% endfor -%}
        {% set prices = ns.result[current_time_index:] -%}

          {{ (((prices[0] * factor_A + factor_B + GSC + WKC + nettarief + heffing + accijns) * VAT_scaling) / 1000) | round(5) }}

      attributes:
        prijzen: >
          {% set factor_A = 1.02 -%}
          {% set factor_B = 0.004 -%}
          {% set GSC = 0.011 -%}
          {% set WKC = 0.00392 -%}
          {% set nettarief = 0.0505027 -%}
          {% set heffing = 0.0019261 -%}
          {% set accijns = 0.04748 -%}
          {% set VAT_scaling = 1.06 -%}

          {% set quarter_index = (now().minute // 5) -%}
          {% set current_hour = now().hour -%}
          {% set current_time_index = current_hour * 12 + quarter_index -%}
          {% set today_prices_data = (state_attr("sensor.nordpool_raw", "raw_today_prices") | map(attribute='price') |list ) -%}
          {% set tomorrow_prices_data = state_attr("sensor.nordpool_raw", "raw_tomorrow_prices") | map(attribute='price') |list -%}

          {% set all_prices = today_prices_data + tomorrow_prices_data  -%}
          {% set ns = namespace(result=[]) -%}
          {% for price in all_prices -%}
            {% set adjusted_price = 0 if (price | float | abs) < 0.12 else price -%}
            {% set ns.result = ns.result + [adjusted_price] * 3 -%}
          {% endfor -%}
          {% set prices = ns.result[current_time_index:] -%}
            {{ prices | map('float')
                      | map('multiply', factor_A)
                      | map('add', factor_B)
                      | map('add', GSC)
                      | map('add', WKC)
                      | map('add', nettarief)
                      | map('add', heffing)
                      | map('add', accijns)
                      | map('multiply', VAT_scaling)
                      | map('multiply', 0.001)
                      | map('round', 5) | list }}

    - name: "Ecopower Injectieprijzen"
      unique_id: 98d961f2-497a-440a-865b-bf2fe1897218
      unit_of_measurement: "EUR/kWh"
      state: >
        {% set factor_C = 0.98 -%}
        {% set factor_D = -0.015 -%}
        {% set quarter_index = (now().minute // 5) -%}
        {% set current_hour = now().hour -%}
        {% set current_time_index = current_hour * 12 + quarter_index -%}
        {% set today_prices_data = (state_attr("sensor.nordpool_raw", "raw_today_prices") | map(attribute='price') |list ) -%}
        {% set tomorrow_prices_data = state_attr("sensor.nordpool_raw", "raw_tomorrow_prices") | map(attribute='price') |list -%}

        {% set all_prices = today_prices_data + tomorrow_prices_data  -%}
        {% set ns = namespace(result=[]) -%}
        {% for price in all_prices -%}
          {% set adjusted_price = 0 if (price | float | abs) < 0.12 else price -%}
          {% set ns.result = ns.result + [adjusted_price] * 3 -%}
        {% endfor -%}
        {% set prices = ns.result[current_time_index:] -%}

          {{ ((prices[0] * factor_C + factor_D) / 1000) | round(5) }}

      attributes:
        prijzen: >
          {% set factor_C = 0.98 -%}
          {% set factor_D = -0.015 -%}

          {% set quarter_index = (now().minute // 5) -%}
          {% set current_hour = now().hour -%}
          {% set current_time_index = current_hour * 12 + quarter_index -%}
          {% set today_prices_data = (state_attr("sensor.nordpool_raw", "raw_today_prices") | map(attribute='price') |list ) -%}
          {% set tomorrow_prices_data = state_attr("sensor.nordpool_raw", "raw_tomorrow_prices") | map(attribute='price') |list -%}

          {% set all_prices = today_prices_data + tomorrow_prices_data  -%}
          {% set ns = namespace(result=[]) -%}
          {% for price in all_prices -%}
            {% set adjusted_price = 0 if (price | float | abs) < 0.12 else price -%}
            {% set ns.result = ns.result + [adjusted_price] * 3 -%}
          {% endfor -%}
          {% set prices = ns.result[current_time_index:] -%}
            {{ prices | map('float')
                      | map('multiply', factor_C)
                      | map('add', factor_D)
                      | map('multiply', 0.001)
                      | map('round', 5) | list }}

# - sensor:
#     - name: "Ecopower Afnameprijzen"
#       unique_id: 16ccc75e-d8ab-4b79-ad3a-af3d289b1724
#       unit_of_measurement: "EUR/kWh"
#       state: >
#         {% set factor_A = 1.02 -%}
#         {% set factor_B = 0.004 -%}
#         {% set GSC = 0.011 -%}
#         {% set WKC = 0.00392 -%}
#         {% set nettarief = 0.0565101 -%}
#         {% set heffing = 0.0019261 -%}
#         {% set accijns = 0.04748 -%}
#         {% set VAT_scaling = 1.06 -%}
#         {% set today = now().strftime('%Y-%m-%d') -%}
#         {% set tomorrow = (now().timestamp() + 86400) | timestamp_custom('%Y-%m-%d') -%}
#         {% set quarter_index = (now().minute // 5) -%}
#         {% set current_hour = now().hour -%}
#         {% set today_prices = (state_attr('sensor.average_electricity_price', 'prices')
#             | selectattr('time', 'search', today)
#             | map(attribute='price')
#             | list)[current_hour:] -%}
#         {% set tomorrow_prices = (state_attr('sensor.average_electricity_price', 'prices')
#             | selectattr('time', 'search', tomorrow)
#             | map(attribute='price')
#             | list) -%}
#         {% set all_prices = today_prices + tomorrow_prices -%}
#         {% set ns = namespace(z=[]) -%}
#         {% for price in all_prices -%}
#           {% set ns.z = ns.z + [price] * 12 -%}
#         {% endfor -%}
#         {% set start = quarter_index -%}
#         {% set prices = ns.z[start:] -%}
#         {{ ((prices[0] * factor_A + factor_B + GSC + WKC + nettarief + heffing + accijns) * VAT_scaling) | round(5) }}
#       attributes:
#         prijzen: >
#           {% set factor_A = 1.02 -%}
#           {% set factor_B = 0.004 -%}
#           {% set GSC = 0.011 -%}
#           {% set WKC = 0.00392 -%}
#           {% set nettarief = 0.0565101 -%}
#           {% set heffing = 0.0019261 -%}
#           {% set accijns = 0.04748 -%}
#           {% set VAT_scaling = 1.06 -%}
#           {% set today = now().strftime('%Y-%m-%d') -%}
#           {% set tomorrow = (now().timestamp() + 86400) | timestamp_custom('%Y-%m-%d') -%}
#           {% set quarter_index = (now().minute // 5) -%}
#           {% set current_hour = now().hour -%}
#           {% set today_prices = (state_attr('sensor.average_electricity_price', 'prices')
#               | selectattr('time', 'search', today)
#               | map(attribute='price')
#               | list)[current_hour:] -%}
#           {% set tomorrow_prices = (state_attr('sensor.average_electricity_price', 'prices')
#               | selectattr('time', 'search', tomorrow)
#               | map(attribute='price')
#               | list) -%}
#           {% set all_prices = today_prices + tomorrow_prices -%}
#           {% set ns = namespace(z=[]) -%}
#           {% for price in all_prices -%}
#             {% set ns.z = ns.z + [price] * 12 -%}
#           {% endfor -%}
#           {% set start = quarter_index -%}
#           {% set prices = ns.z[start:] -%}
#           # {{ prices | map('float')
#           #           | map('multiply', factor_A)
#           #           | map('add', factor_B)
#           #           | map('add', GSC)
#           #           | map('add', WKC)
#           #           | map('add', nettarief)
#           #           | map('add', heffing)
#           #           | map('add', accijns)
#           #           | map('multiply', VAT_scaling)
#           #           | map('round', 5) | list }}

#     - name: "Ecopower Injectieprijzen"
#       unique_id: 98d961f2-497a-440a-865b-bf2fe1897218
#       unit_of_measurement: "EUR/kWh"
#       state: >
#         {% set factor_C = 0.98 -%}
#         {% set factor_D = -0.015 -%}
#         {% set today = now().strftime('%Y-%m-%d') -%}
#         {% set tomorrow = (now().timestamp() + 86400) | timestamp_custom('%Y-%m-%d') -%}
#         {% set quarter_index = (now().minute // 5) -%}
#         {% set current_hour = now().hour -%}
#         {% set today_prices = (state_attr('sensor.average_electricity_price', 'prices')
#             | selectattr('time', 'search', today)
#             | map(attribute='price')
#             | list)[current_hour:] -%}
#         {% set tomorrow_prices = (state_attr('sensor.average_electricity_price', 'prices')
#             | selectattr('time', 'search', tomorrow)
#             | map(attribute='price')
#             | list) -%}
#         {% set all_prices = today_prices + tomorrow_prices -%}
#         {% set ns = namespace(z=[]) -%}
#         {% for price in all_prices -%}
#           {% set ns.z = ns.z + [price] * 12 -%}
#         {% endfor -%}
#         {% set start = quarter_index -%}
#         {% set prices = ns.z[start:] -%}
#         {{ (prices[0] * factor_C + factor_D) | round(5) }}
#       attributes:
#         prijzen: >
#           {% set factor_C = 0.98 -%}
#           {% set factor_D = -0.015 -%}
#           {% set today = now().strftime('%Y-%m-%d') -%}
#           {% set tomorrow = (now().timestamp() + 86400) | timestamp_custom('%Y-%m-%d') -%}
#           {% set quarter_index = (now().minute // 5) -%}
#           {% set current_hour = now().hour -%}
#           {% set today_prices = (state_attr('sensor.average_electricity_price', 'prices')
#               | selectattr('time', 'search', today)
#               | map(attribute='price')
#               | list)[current_hour:] -%}
#           {% set tomorrow_prices = (state_attr('sensor.average_electricity_price', 'prices')
#               | selectattr('time', 'search', tomorrow)
#               | map(attribute='price')
#               | list) -%}
#           {% set all_prices = today_prices + tomorrow_prices -%}
#           {% set ns = namespace(z=[]) -%}
#           {% for price in all_prices -%}
#             {% set ns.z = ns.z + [price] * 12 -%}
#           {% endfor -%}
#           {% set start = quarter_index -%}
#           {% set prices = ns.z[start:] -%}
#           {{ prices | map('float') | map('multiply', factor_C) | map('add', factor_D) | map('round', 5) | list }}

#     - name: "Price list length"
#       unique_id: 3ac05511-a002-4d3a-b104-2d57ada50d07
#       unit_of_measurement: "st"
#       state: >
#         {% set today = now().strftime('%Y-%m-%d') -%}
#         {% set tomorrow = (now().timestamp() + 86400) | timestamp_custom('%Y-%m-%d') -%}
#         {% set quarter_index = (now().minute // 5) -%}
#         {% set current_hour = now().hour -%}
#         {% set today_prices = (state_attr('sensor.average_electricity_price', 'prices')
#             | selectattr('time', 'search', today)
#             | map(attribute='price')
#             | list)[current_hour:] -%}
#         {% set tomorrow_prices = (state_attr('sensor.average_electricity_price', 'prices')
#             | selectattr('time', 'search', tomorrow)
#             | map(attribute='price')
#             | list) -%}
#         {% set all_prices = today_prices + tomorrow_prices -%}
#         {% set ns = namespace(z=[]) -%}
#         {% for price in all_prices -%}
#           {% set ns.z = ns.z + [price] * 12 -%}
#         {% endfor -%}
#         {% set start = quarter_index -%}
#         {% set prices = ns.z[start:] -%}
#         {{ prices | length }}
