- sensor:
    - name: Warmtepompboiler uren
      unique_id: 8225bcd3-62ca-40af-8891-ba06a95eed91
      unit_of_measurement: "uur"
      state: >
        {% set temp = (states("sensor.thermostaat") | float(45) * 4) | round(0) / 4 -%}
        {% if states("input_boolean.warm_water_starten") == 'on' -%}
            {% if states("input_boolean.op_verlof") == 'off' -%}
              {% if (states("sensor.open_meteo_voorspelling_resterend_vandaag") | float(0)) > 2 -%}
                {% set hours = (max(0, (51 - temp) / 5) * 4) | round(0) / 4 -%}
              {% else -%}
                {% set hours = (max(0, (50 - temp) / 5) * 4) | round(0) / 4 -%}
              {% endif -%}
            {% else -%}
              {% set hours = (max(0, (46 - temp) / 5) * 4) | round(0) / 4 -%}
            {% endif -%}
            {% if is_state("binary_sensor.warmtepompboiler_aan", "on") -%}
              {{ hours }}
            {% else -%}
              {{ hours if hours >= 1 else 0 }}
            {% endif -%}
        {% else -%}
          0
        {% endif -%}
      # state: >
      #   {% set horizon = states('sensor.prediction_horizon')|int(0) / 12 -%}
      #   {% set temp = (states("sensor.thermostaat") | float(45) * 4) | round(0) / 4 -%}
      #   {% if states("input_boolean.warm_water_starten") == 'on' -%}
      #     {% if states("input_boolean.op_verlof") == 'off' -%}
      #       {% if (states("sensor.open_meteo_voorspelling_resterend_vandaag") | float(0)) > 2 -%}
      #         {% set hours = max(0, (53 - temp) / 5) -%}
      #       {% else -%}
      #         {% set hours = max(0, (52 - temp) / 5) -%}
      #       {% endif -%}
      #     {% else -%}
      #       {% set hours = max(0, (46 - temp) / 5) -%}
      #     {% endif -%}
      #     {% if hours|float > horizon -%}
      #       {{ horizon }}
      #     {% else -%}
      #       {% if states("binary_sensor.warmtepompboiler_aan") == "on" -%}
      #         {{ (hours|float * 4) | round(0) / 4 }}
      #       {% else -%}
      #         {{ (hours|float * 4) | round(0) / 4 if ((hours|float * 4) | round(0) / 4) > 1 else 0}}
      #       {% endif -%}
      #     {% endif -%}
      #   {% else -%}
      #     0
      #   {% endif -%}


    - name: Warm water startuur
      unique_id: f4450d07-ad80-4ed5-a96a-852c84fec6ca
      state: >
        {% from 'easy_time.jinja' import easy_relative_time -%}
        {% set load = (state_attr('sensor.emhass_warmtepompboiler', 'deferrables_schedule')
                |map(attribute='emhass_warmtepompboiler')
                |list) -%}
        {% set time = (state_attr('sensor.emhass_warmtepompboiler', 'deferrables_schedule')
                |map(attribute='date')
                |list) -%}
        {% if is_state("input_boolean.emhass_warmtepompboiler", "on") -%}
          Staat op
        {% else -%}
          {% set new_list = namespace(all=[]) -%}
            {% for i in range (load | length) -%}
              {% if load[i] | float(0) > 1 -%}
                {{ (easy_relative_time(time [i], max_period='minute', language='nl')) }}
                {% break -%}
              {% endif -%}
            {% endfor -%}
          {% endif -%}
      availability: >-
        {{ states('sensor.emhass_warmtepompboiler') | is_number }}
    
    - name: Warmtepompboiler start timesteps
      unique_id: b9a1f40e-00d6-48b4-9a9b-b7d558e78357
      unit_of_measurement: 5m
      state: >
        {% if (as_timestamp(now()) - states("sensor.warmtepompboiler_is_gestopt_op")|float(0)) < 1500 -%}
          6
        {% else -%}
          0
        {% endif -%}
    
    - name: Warmtepompboiler end timesteps
      unique_id: 108e2881-9ac7-49ef-baab-2631da9ab3f4
      unit_of_measurement: 5m
      state: >
        {% set uren = states("sensor.warmtepompboiler_uren") | float(0) -%}
        {% set operate = uren * 12 -%}
        {% set hour = now().hour -%}
        {% set minute = now().minute -%}
        {% set block = hour * 12 + (minute // 5) -%}
        {% set remaining = 288 - block -%}
        {% if states("sensor.thermostaat") | int < 43 or states("binary_sensor.warmtepompboiler_aan") == "on" -%}
          {{ operate | int }}
        {% elif uren == 0 -%}
          {{ 288 }}
        {% elif uren >= 1.5 -%}
          {{ min(operate, remaining) | int }}
        {% else -%}
          {% set factor = uren / 1.5 -%}
          {% set max_blocks = 288 - (factor * (288 - operate)) -%}
          {{ min(max_blocks, remaining) | int }}
        {% endif -%}
      # state: >
      #   {% set operate = (states("sensor.warmtepompboiler_uren") | float(0)) * 12 -%}
      #   {% set hour = now().hour -%}
      #   {% set minute = now().minute -%}
      #   {% set block = hour * 12 + (minute // 5) -%}
      #   {% set remaining = 288 - block -%}
      #   {% if states("sensor.thermostaat") | int < 43  or states("binary_sensor.warmtepompboiler_aan") == "on" -%}
      #     {{ operate | int }}
      #   {% elif hour > 21 or hour < 8 -%}
      #     {{ max(operate, 216) | int }}
      #   {% else -%}
      #     {{ max(operate, remaining) | int }}
      #   {% endif -%}
