alias: "Doorbell Notifications"
id: 642ea33c-f454-4b4c-a4bb-12ecb35d6868
triggers:
  trigger: state
  entity_id: switch.deurbel
  to: "on"
actions:
  - action: music_assistant.play_announcement
    target:
      entity_id:
        - media_player.mass_keuken
        - media_player.mass_badkamer
    data:
      announce_volume: 49
      url: >
        {% set number = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] | random | string -%}
        {% set sound = "deurbel"+number+".mp3" -%}
          {{ "http://192.168.6.54:8123/local/sounds/deurbel/"+sound }}

  - if:
      - condition: state
        entity_id: binary_sensor.garage_bezetting
        state: "on"
    then:
      - action: light.toggle
        target:
          entity_id:
            - light.garage
            - light.garage_werkbank
      - delay:
          seconds: 1
      - action: light.toggle
        target:
          entity_id:
            - light.garage
            - light.garage_werkbank

  - if:
      - condition: state
        entity_id: binary_sensor.tuin_bezetting
        state: "on"
    then:
      - action: light.toggle
        target:
          entity_id:
            - light.alle_tuinverlichting
      - delay:
          seconds: 1
      - action: light.toggle
        target:
          entity_id:
            - light.alle_tuinverlichting
  - delay:
      seconds: 10
