alias: EMHASS data
id: 684e7c96-7eb8-41fa-b81c-e3c97e234b56
mode: parallel
triggers:
  - trigger: time
    at: "01:31:00"
    id: "fit"
  - trigger: time
    at: "00:06:00"
    id: "prediction"
  - trigger: time_pattern
    minutes: /5
    id: mpc
  - trigger: homeassistant
    event: start
    id: start

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: mpc
        sequence:
          - delay:
              seconds: 3
          - action: script.emhass_mpc_models
          - action: script.emhass_publish_models

      - conditions:
          - condition: trigger
            id: fit
        sequence:
          - action: script.emhass_fit_models

      - conditions:
          - condition: trigger
            id: start
        sequence:
          - action: script.emhass_publish_models

      - conditions:
          - condition: trigger
            id: prediction
        sequence:
          - action: script.fit_heating_hours
          - action: script.predict_heating_hours

