alias: EMHASS data
id: 684e7c96-7eb8-41fa-b81c-e3c97e234b56
mode: parallel
trigger:
  - platform: time
    at: "01:31:00"
    id: "fit"
  - platform: time
    at: "00:06:00"
    id: "prediction"
  - platform: time_pattern
    minutes: /5
    id: mpc
  - platform: homeassistant
    event: start
    id: start
  # - platform: time
  #   at: input_datetime.emhass_data
  #   id: data
actions:
  - choose:
      # - conditions:
      #     - condition: trigger
      #       id: data
      #   sequence:
      #     - delay:
      #         seconds: 2
      #     - action: rest_command.publish_data
      #       data:
      #         prefix: ""
          # - condition: state
          #   entity_id: input_boolean.emhass_testen
          #   state: "on"
          # - condition: state
          #   entity_id: input_boolean.emhass_publish_testen
          #   state: "on"
          # - action: rest_command.publish_data_test
          #   data:
          #     prefix: ""
      - conditions:
          - condition: trigger
            id: mpc
        sequence:
          - delay:
              seconds: 2
          - action: script.emhass_mpc_publish
          - delay:
              seconds: 5
          - action: script.emhass_mpc_publish_models
          # - action: rest_command.naive_mpc_optim
          #   data:
          #     payload: >
          #       {{ state_attr("sensor.emhass_mpc", "mpc") }}
          # - action: input_datetime.set_datetime
          #   data:
          #     datetime: >
          #       {{ now() + timedelta(seconds=5) }}
          #   target:
          #     entity_id: input_datetime.emhass_data
          
          - condition: state
            entity_id: input_boolean.emhass_testen
            state: "on"
          - action: script.emhass_mpc_and_publish_test
            # data:
            #   payload: >
            #     {{ state_attr("sensor.emhass_mpc_test", "mpc") }}
      - conditions:
          - condition: trigger
            id: fit
        sequence:
          - action: script.emhass_fit_tune_model
          - action: script.emhass_fit_models
          # - action: rest_command.forecast_model_fit_load_zonder_wp
          - condition: state
            entity_id: input_boolean.emhass_testen
            state: "on"
          - action: script.emhass_fit_test_models
          - action: script.emhass_tune_test_models
      - conditions:
          - condition: trigger
            id: start
        sequence:
          - action: script.emhass_mpc_publish
          # - action: rest_command.publish_data
          #   data:
          #     prefix: ""
          # - condition: state
          #   entity_id: input_boolean.emhass_publish_testen
          #   state: "on"
          # - action: rest_command.publish_data_test
          #   data:
          #     prefix: ""
      - conditions:
          - condition: trigger
            id: prediction
        sequence:
          - service: script.fit_heating_hours
          - condition: state
            entity_id: input_boolean.emhass_testen
            state: "on"
          - action: rest_command.fit_heating_hours_test
          - delay:
              seconds: 14
          - action: rest_command.predict_heating_hours_test
            data:
              buiten_temp: >
                {{temp_stats.statistics["sensor.buiten_temperatuur"][0].mean | float(0) | round(2)}}
              binnen_temp: >
                {{temp_stats.statistics["sensor.benedentemperatuur_gefilterd"][0].mean | float(0) | round(2)}}
      
      # - conditions:
      #     - condition: trigger
      #       id: dayahead
      #   sequence:
      #     - action: rest_command.dayahead_optim
      #     - delay:
      #         seconds: 5
      #     - action: rest_command.publish_data
      #       data:
      #         prefix: "dh_"
      #     - condition: state
      #       entity_id: input_boolean.emhass_testen
      #       state: "on"
      #     - action: rest_command.dayahead_optim_test
      #     - delay:
      #         seconds: 5
      #     - action: rest_command.publish_data_test
      #       data:
      #         prefix: "dh_"
      # - conditions:
      #     - condition: trigger
      #       id: night
      #     - alias: "snachts"
      #       condition: template
      #       value_template: >
      #         {{ now().hour is in [0, 1, 2, 3, 4, 5] }}
      #   sequence:
      #     - delay:
      #         seconds: 2
      #     - action: rest_command.naive_mpc_optim
      #       data:
      #         payload: >
      #           {{ state_attr("sensor.emhass_mpc", "mpc") }}
      #     - action: input_datetime.set_datetime
      #       data:
      #         datetime: >
      #           {{ now() + timedelta(seconds=5) }}
      #       target:
      #         entity_id: input_datetime.emhass_data
      #     - condition: state
      #       entity_id: input_boolean.emhass_testen
      #       state: "on"
      #     - action: rest_command.naive_mpc_optim_test
