id: 4fe64d7b-270f-4da6-be01-8aa8dbb1f6a3
alias: Emhass notification
description: ""
triggers:
  - trigger: state
    entity_id: script.emhass_grid_follower
    from: "off"
    to: "on"
actions:
  - action: notify.mobile_app_gphone
    data:
      message: Emhass grid follower gestart
