alias: Prediction set input_number
id: b81cb250-5e2b-46e0-984b-f09c1a4eec92
mode: parallel
triggers:
  - trigger: state
    entity_id:
      - sensor.voorspelde_uren_randomforest
      - sensor.voorspelde_uren_adaboost
      - sensor.voorspelde_uren_gradientboosting
      - sensor.voorspelde_uren_extratrees
      - sensor.voorspelde_uren_svr
      - sensor.voorspelde_uren_decisiontree
      - sensor.voorspelde_uren_kneighbors
      - sensor.voorspelde_uren_elasticnet
      - sensor.voorspelde_uren_lasso
      - sensor.voorspelde_uren_ridge
      - sensor.voorspelde_uren_linear

actions:
  - variables:
      sensor: "{{ trigger.entity_id }}"
      value: "{{ states(sensor) | float(0) }}"
      clean_value: "{{ [value, 0] | max | round(2) }}"
      input_number: >
        {{ sensor.replace('sensor.', 'input_number.') }}

  - choose:
      - conditions: "{{ sensor == 'sensor.voorspelde_uren_randomforest' }}"
        sequence:
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.verwarming_starten

  - action: input_number.set_value
    target:
      entity_id: "{{ input_number }}"
    data:
      value: "{{ clean_value }}"
