alias: gang action
id: 6b406fef-f5c4-4f5a-8c95-f907fb74d67b
triggers:
  - trigger: event
    event_type: mobile_app_notification_action
    event_data:
      action: "GANG"

actions:
  - action: automation.turn_off
    metadata: {}
    data:
      stop_actions: true
    target:
      entity_id: automation.gang_verklikker
