alias: poort action
id: 33235461-2f5e-4189-8e3c-1c13df040758
triggers:
  - trigger: event
    event_type: mobile_app_notification_action
    event_data:
      action: "POORT"

actions:
  - action: switch.turn_off
    target:
      entity_id: switch.incognito
