alias: Achtergevel sluiten #Sunscreen down/uitklappen
id: 9d85fbd0-a081-4afa-8c56-d9216ea52a37
trigger:
  - platform: numeric_state
    entity_id: sensor.buiten_lichtsterkte
    for:
      minutes: 5
    above: 15000
  - platform: time_pattern
    minutes: "/10"
    seconds: 00
  - platform: template
    value_template: >
      {{ states("sensor.buiten_lichtsterkte") | int(0) > 5000 and
          now().hour < 9 }}
    id: ochtend
condition:
  condition: and # all conditions need to be TRUE before action is executed.
  conditions:
    # Sun based conditions
    - condition: numeric_state
      entity_id: sensor.sun_azimut
      above: 70
      below: 200
    - condition: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      above: 10
    - condition: numeric_state
      entity_id: sensor.zonne_energie_gefilterd_lowpass
      above: 580
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.buiten_lichtsterkte
          above: 15000
        - condition: trigger
          id: ochtend

    # Weather based conditions
    - condition: template
      value_template: >
        {{ states("sensor.windsnelheid") | int(0) < 40 }}
    - condition: template
      value_template: >
        {{ states("sensor.windvlaag") | int(0) < 60 }}
    - condition: template
      value_template: >
        {% if states("sensor.regen_komende_10_minuten") != "unknown" and states("sensor.regen_komende_10_minuten") != "unavailable" %}
          {{ states("sensor.regen_komende_10_minuten") | float < 0.15 }}
        {% else %}
          {{ states("sensor.neerslagverwachting_gemiddeld")  | float < 0.15 }}
        {% endif %}
    - condition: template
      value_template: >
        {% if states("sensor.neerslag_zandhoven") != "unknown" and states("sensor.neerslag_zandhoven") != "unavailable" %}
          {{ states("sensor.neerslag_zandhoven") | float < 0.15 }}
        {% else %}
          {{ states("sensor.neerslagintensiteit")  | float < 0.15 }}
        {% endif %}

    - condition: numeric_state
      entity_id: sensor.max_uv_index
      above: 3 # This indicates direct sunlight on my location (as in: not cloudy)

    # Temperature based conditions
    - condition: numeric_state
      entity_id: sensor.buitentemperatuur_gefilterd
      above: 15 # only if outdoor temperature is above x then allowed to roll out
    - condition: numeric_state
      entity_id: sensor.gemiddelde_temp_beneden
      above: 22 # only if indoor temperature is above x then allowed to roll out

    - condition: template
      value_template: >
        {{ states("sensor.max_temperatuur_buiten_voorspelling_12u") | float(0) > (states("sensor.gemiddelde_temp_beneden") | float(0) - 2) }}

    # Time based conditions
    - condition: template
      value_template: "{{ now().month > 3 }}" # Starting April
    - condition: template
      value_template: "{{ now().month < 10 }}" # Ending October

    # No others screens are closing
    - condition: state
      entity_id: script.zijgevel_sluiten
      state: "off"

    - condition: state
      entity_id: input_boolean.achtergevel_closed
      state: "off"
    - condition: template
      value_template: >
        {{ state_attr("cover.keuken_1", "current_position") > 50 }}
    - condition: template
      value_template: >
        {{ state_attr("cover.keuken_2", "current_position") > 50 }}
    - condition: template
      value_template: >
        {{ state_attr("cover.slaapkamer", "current_position") > 50 }}

actions:
  - action: script.achtergevel_sluiten
