alias: Zonnewering winter
id: 12930512-2ad9-43f8-a711-1538e0d1fb47
trigger:
  - platform: state
    entity_id: sensor.dark_inside
    to: "true"
    id: sluiten
    for:
      minutes: 5
  - platform: template
    id: openen
    value_template: >
      {{ states("sensor.windsnelheid") | int(0) > 40 }}
  - platform: template
    id: openen
    value_template: >
      {{ states("sensor.windvlaag") | int(0) > 60 }}
  - platform: template
    value_template: >
      {% if states("sensor.regen_komende_10_minuten") != "unknown" and states("sensor.regen_komende_10_minuten") != "unavailable" %}
        {{ states("sensor.regen_komende_10_minuten") | float > 0 }}
      {% else %}
        {{ states("sensor.neerslagverwachting_gemiddeld")  | float > 0 }}
      {% endif %}
    id: openen
  - platform: template
    value_template: >
      {% if states("sensor.neerslag_zandhoven") != "unknown" and states("sensor.neerslag_zandhoven") != "unavailable" %}
        {{ states("sensor.neerslag_zandhoven") | float > 0 }}
      {% else %}
        {{ states("sensor.neerslagintensiteit")  | float > 0 }}
      {% endif %}
    id: openen
  - platform: state
    entity_id: sensor.dark_inside
    to: "false"
    id: openen
  - platform: state
    entity_id: binary_sensor.kans_op_aanvriezen
    to: "on"
    id: openen
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: sluiten
          - condition: numeric_state
            entity_id: sensor.min_temperatuur_buiten_voorspelling_12u
            below: 10
          - condition: time
            after: "15:00:00"
          - condition: template
            value_template: >
              {{ states("sensor.regen_komende_10_minuten")|float(0) == 0 }}
          - condition: template
            value_template: >
              {{ now().month >= 9 or now().month <= 4 }}
          - condition: template
            value_template: >
              {{ states("binary_sensor.kans_op_aanvriezen") == "off" }}
          - condition: template
            value_template: >
              {{ states("sensor.windsnelheid") | int(0) < 40 }}
          - condition: template
            value_template: >
              {{ states("sensor.windvlaag") | int(0) < 60 }}
        sequence:
          - action: script.achtergevel_sluiten
          - delay:
              seconds: 10
          - action: script.zijgevel_sluiten
          # - action: cover.close_cover
          #   target:
          #     entity_id:
          #       - cover.keuken_1
          #       - cover.keuken_2
          #       - cover.living
          #       - cover.slaapkamer
          #       - cover.slaapkamer_noor
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.nacht_closed
      - conditions:
          - condition: trigger
            id: openen
          # - condition: numeric_state
          #   entity_id: sensor.min_temperatuur_buiten_voorspelling_12u
          #   below: 12
          - condition: template
            value_template: >
              {{ states("cover.keuken_1") != "open" or
                states("cover.keuken_2") != "open" or
                states("cover.living") != "open" or
                states("cover.slaapkamer") != "open" or
                states("cover.slaapkamer_noor") != "open" }}
        sequence:
          - action: script.achtergevel_openen
          - delay:
              seconds: 10
          - action: script.zijgevel_openen
          - delay:
              minutes: 3
          - action: script.achtergevel_openen
          - delay:
              seconds: 10
          - action: script.zijgevel_openen
          # - action: cover.open_cover
          #   target:
          #     entity_id:
          #       - cover.keuken_1
          #       - cover.keuken_2
          #       - cover.living
          #       - cover.slaapkamer
          #       - cover.slaapkamer_noor
          - action: input_boolean.turn_off
            target:
              entity_id: input_boolean.nacht_closed
