alias: Zijgevel openen #Sunscreen up/inklappen
id: 20cf3eda-0ede-4c90-b0b8-33e1853f7114
triggers:
  # Sun based triggers
  # - trigger: numeric_state
  #   entity_id: sensor.sun_azimut
  #   above: 330
  - trigger: template
    value_template: >
      {{ states("sensor.sun_azimut") | int > 330 and
        states("sensor.buiten_temperatuur") | int(0) > 10 }}
  # - trigger: numeric_state
  #   entity_id: sensor.sun_elevation
  #   below: -10
  - trigger: template
    value_template: >
      {{ states("sensor.sun_elevation") | int < -10 and
        states("sensor.buiten_temperatuur") | int(0) > 10 }}
  - trigger: state
    entity_id: sensor.dark_inside
    to: "true"
    for:
      minutes: 5
  - trigger: numeric_state
    entity_id: sensor.buiten_lichtsterkte
    below: 10000
    for:
      minutes: 5

  # Weather based triggers
  - trigger: template
    value_template: >
      {{ states("sensor.openweathermap_windsnelheid") | int(0) > 40 }}
  - trigger: template
    value_template: >
      {{ states("sensor.openweathermap_windvlaag_snelheid") | int(0) > 60 }}
  # - trigger: template
  #   value_template: >
  #     {{ states("sensor.buiten_lichtsterkte") | float(0) < 4000 and
  #       (states("sensor.solcast_forecast_next_hour") | float(0) < 1000 or
  #       states("sensor.solcast_forecast_this_hour") | float(0) < 1000) }}

  - trigger: template
    value_template: >
      {% if states("sensor.regen_komende_10_minuten") != "unknown" and states("sensor.regen_komende_10_minuten") != "unavailable" %}
        {{ states("sensor.regen_komende_10_minuten") | float > 0.80 }}
      {% endif %}
  - trigger: template
    value_template: >
      {% if states("sensor.neerslag_zandhoven") != "unknown" and states("sensor.neerslag_zandhoven") != "unavailable" %}
        {{ states("sensor.neerslag_zandhoven") | float > 0.40 }}
      {% else %}
        {{ states("sensor.openweathermap_rain_intensity")  | float > 0.40 }}
      {% endif %}

conditions:
  - condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.zijgevel_closed
        state: "on"
      - condition: template
        value_template: >
          {{ state_attr("cover.living", "current_position") < 50 }}
      - condition: template
        value_template: >
          {{ state_attr("cover.slaapkamer_noor", "current_position") < 50 }}
  - condition: state
    entity_id: input_boolean.nacht_closed
    state: "off"
    
actions:
  - action: script.zijgevel_openen
  # - action: notify.mobile_app_gphone
  #   data_template:
  #     message: "Het zonnescherm zijgevel geopend, reden {{trigger.entity_id}} "
  - delay:
      minutes: 5
  - action: script.zijgevel_openen
