# =============================================================================
# MAANDELIJKSE GEMIDDELDEN (30 dagen)
# =============================================================================
- platform: statistics
  name: Adaboost error 30d
  unique_id: 7237c9a3-52a7-47b3-9669-02c5c2358d18
  entity_id: input_number.error_adaboost
  state_characteristic: mean
  max_age:
    days: 30

- platform: statistics
  name: Gradientboosting error 30d
  unique_id: 0a5efafe-2995-4bd3-9c23-cb3ad701d7fa
  entity_id: input_number.error_gradientboosting
  state_characteristic: mean
  max_age:
    days: 30

- platform: statistics
  name: Extratrees error 30d
  unique_id: 1a454a2c-14d7-41d5-8ff7-a87d085b5cde
  entity_id: input_number.error_extratrees
  state_characteristic: mean
  max_age:
    days: 30

- platform: statistics
  name: Randomforest error 30d
  unique_id: 984cb06f-2564-4ec8-939e-a69746f3ea46
  entity_id: input_number.error_randomforest
  state_characteristic: mean
  max_age:
    days: 30

- platform: statistics
  name: SVR error 30d
  unique_id: 627af776-2656-46fc-ad71-08c2a76fd7a9
  entity_id: input_number.error_svr
  state_characteristic: mean
  max_age:
    days: 30

- platform: statistics
  name: Decisiontree error 30d
  unique_id: 620facb8-5482-44a6-868b-fc1b6b763e75
  entity_id: input_number.error_decisiontree
  state_characteristic: mean
  max_age:
    days: 30

- platform: statistics
  name: Kneighbors error 30d
  unique_id: ced655f3-0a34-4053-b6f4-3ce107b7e40a
  entity_id: input_number.error_kneighbors
  state_characteristic: mean
  max_age:
    days: 30

- platform: statistics
  name: Elasticnet error 30d
  unique_id: 2ccf9669-62dc-40f3-ab35-00ea1a0cdf7b
  entity_id: input_number.error_elasticnet
  state_characteristic: mean
  max_age:
    days: 30

- platform: statistics
  name: Lasso error 30d
  unique_id: 3618aae2-da7b-455b-8cf7-58d4401576ba
  entity_id: input_number.error_lasso
  state_characteristic: mean
  max_age:
    days: 30

- platform: statistics
  name: Ridge error 30d
  unique_id: 575d01ee-c32a-424f-b179-cbd41823a7af
  entity_id: input_number.error_ridge
  state_characteristic: mean
  max_age:
    days: 30

- platform: statistics
  name: Linear error 30d
  unique_id: b38d3605-991d-4ae1-b449-95557373ed10
  entity_id: input_number.error_linear
  state_characteristic: mean
  max_age:
    days: 30

# =============================================================================
# WEEKLY GEMIDDELDEN (7 dagen)
# =============================================================================

- platform: statistics
  name: Adaboost error 7d
  unique_id: 04de20fc-e484-41d2-8194-9c17a0773c44
  entity_id: input_number.error_adaboost
  state_characteristic: mean
  max_age:
    days: 7

- platform: statistics
  name: Gradientboosting error 7d
  unique_id: 0f8d4518-01ef-4c63-888a-2812979cb9a7
  entity_id: input_number.error_gradientboosting
  state_characteristic: mean
  max_age:
    days: 7

- platform: statistics
  name: Extratrees error 7d
  unique_id: 4f562b45-9d3c-42e3-92fd-184d52bdcd0e
  entity_id: input_number.error_extratrees
  state_characteristic: mean
  max_age:
    days: 7

- platform: statistics
  name: Randomforest error 7d
  unique_id: 4f538228-3967-45dc-9315-00de40969591
  entity_id: input_number.error_randomforest
  state_characteristic: mean
  max_age:
    days: 7

- platform: statistics
  name: Decisiontree error 7d
  unique_id: f254a36f-8e7f-412e-8c94-5f7560fd3ca1
  entity_id: input_number.error_decisiontree
  state_characteristic: mean
  max_age:
    days: 7

- platform: statistics
  name: SVR error 7d
  unique_id: cb4d526c-4b93-4d55-a659-1441cd6b885b
  entity_id: input_number.error_svr
  state_characteristic: mean
  max_age:
    days: 7

- platform: statistics
  name: Kneighbors error 7d
  unique_id: e46afbfc-e15a-4b52-a996-0c2c628f07af
  entity_id: input_number.error_kneighbors
  state_characteristic: mean
  max_age:
    days: 7

- platform: statistics
  name: Elasticnet error 7d
  unique_id: f5d327ad-f5a0-4747-9b51-24ce56b78983
  entity_id: input_number.error_elasticnet
  state_characteristic: mean
  max_age:
    days: 7

- platform: statistics
  name: Lasso error 7d
  unique_id: 35a78df4-c973-43ef-9e63-8dba2d9c9690
  entity_id: input_number.error_lasso
  state_characteristic: mean
  max_age:
    days: 7

- platform: statistics
  name: Ridge error 7d
  unique_id: 8242d7c6-92eb-483e-81d7-63ccbaf1fb13
  entity_id: input_number.error_ridge
  state_characteristic: mean
  max_age:
    days: 7

- platform: statistics
  name: Linear error 7d
  unique_id: 45f184a9-b128-40a5-9731-5d0a59901502
  entity_id: input_number.error_linear
  state_characteristic: mean
  max_age:
    days: 7
