substitutions:
  devicename: buitenv2
  platform: esp8266
  board: nodemcuv2
  upper_devicename: Buiten

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base_new_style.yaml
  
i2c:
  sda: D2
  scl: D1
  scan: true
  id: bus_a

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

switch:
  - platform: gpio
    pin:
      number: D5
    name: "Weerstation fan"
    # inverted: true
    id: fan
    restore_mode: RESTORE_DEFAULT_OFF

# binary_sensor:
#   - platform: template
#     name: "Kans op aanvriezen"
#     # Als het dauwpunt lager is dan de temperatuur die de voorruit en de lucht eromheen 's nachts bereiken, zult u niet wakker worden met een bevroren voorruit. Als het dauwpunt hoger is dan die temperaturen, zult u dat wel (ervan uitgaande dat de temperatuur onder het vriespunt ligt).
#     lambda: |-
#       if ((id(dauwpunt).state > id(ha_temp).state) && (id(ha_temp).state < 1)) {
#         return true;
#       } else {
#         return false;
#       }


sensor:
  - platform: bh1750
    name: "Buiten lichtsterkte"
    address: 0x23
    update_interval: 60s

  - platform: homeassistant
    entity_id: sensor.poort_luchtvochtigheid
    id: ha_humidity
    internal: true
  
  - platform: homeassistant
    entity_id: sensor.buiten_temperatuur
    id: ha_temp
    internal: true

  - platform: bme280_i2c
    temperature:
      name: "Buiten temperatuur"
      id: bme280_temperature
      oversampling: 1x
    pressure:
      name: "Buiten luchtdruk"
      id: bme280_pressure
      oversampling: 1x

    address: 0x76
    i2c_id: bus_a
    update_interval: 60s

  - platform: template
    name: "Buiten dauwpunt"
    id: dauwpunt
    lambda: |-
      return (243.5*(log(id(ha_humidity).state/100)+((17.67*id(ha_temp).state)/
      (243.5+id(ha_temp).state)))/(17.67-log(id(ha_humidity).state/100)-
      ((17.67*id(ha_temp).state)/(243.5+id(ha_temp).state))));
    unit_of_measurement: °C
    icon: "mdi:thermometer-alert"
  
  - platform: absolute_humidity
    name: "${upper_devicename} absolute luchtvochtigheid"
    temperature: ha_temp
    humidity: ha_humidity
