substitutions:
  devicename: keukenbt
  upper_devicename: keukenBT
  platform: esp32
  board: esp32dev

esp32:
  framework:
    type: esp-idf

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base_new_style.yaml

wifi:
  power_save_mode: light

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: false

bluetooth_proxy:
  active: true
