substitutions:
  devicename: poort2
  upper_devicename: Poort
  platform: esp32
  board: esp32dev

esp32:
  framework:
    type: esp-idf

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base_new_style.yaml
  
wifi:
  # ...
  power_save_mode: light

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: false

bluetooth_proxy:
  active: true

i2c:
  - id: bus_a
    sda: 21
    scl: 22
    
logger:
  level: DEBUG

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO18
      inverted: true
      mode:
        input: true
        pullup: true
    name: ${upper_devicename}
    device_class: motion
    filters:
      - delayed_on: 100ms
      - delayed_off: 3s
    
sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""
    
  - platform: sht3xd
    temperature:
      name: ${upper_devicename} temperatuur
      internal: false
    humidity:
      name: ${upper_devicename} luchtvochtigheid
    address: 0x44
    update_interval: 60s
    i2c_id: bus_a 

switch:
  - platform: gpio
    pin:
      number: GPIO16
      # inverted: yes
    name: "Pries ${devicename}"
    restore_mode: RESTORE_DEFAULT_OFF
    device_class: outlet