substitutions:
  devicename: stopcontacten-buiten-garage
  platform: esp8266
  board: nodemcuv2
  upper_devicename: Esp garage

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base_new_style.yaml
  
switch:
  - platform: gpio
    pin:
      number: D0
    name: "Stopcontacten garage"
    id: stopcontacten
    restore_mode: RESTORE_DEFAULT_ON
  - platform: gpio
    pin:
      number: D2
    name: "Garage verwarming"
    id: heater
    restore_mode: RESTORE_DEFAULT_ON

output:
  - platform: gpio
    pin:
      number: D5
    id: sfeer
  - platform: gpio
    pin:
      number: D6
    id: sjotterbak
  - platform: gpio
    pin:
      number: D7
    id: afdak
  - platform: gpio
    pin:
      number: D8
    id: vogelpik 

light:
  - platform: binary
    name: "Vogelpik"
    output: vogelpik
  - platform: binary
    name: "Garage sfeerverlichting"
    output: sfeer
  - platform: binary
    name: "Garage sjotterbak"
    output: sjotterbak
  - platform: binary
    name: "Afdak verlichting"
    output: afdak
    
binary_sensor:
  - platform: gpio
    pin: D1
    name: "Beweging in garage"
    device_class: motion
    filters:
      - delayed_on_off: 1s
