substitutions:
  devicename: verwarming-3
  upper_devicename: Esp verwarming
  ssid: !secret ssid-living
  manual_ip: 192.168.79.144
  platform: esp32
  board: esp32dev

esp32:
  framework:
    type: esp-idf

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base_new_style.yaml

wifi:
  power_save_mode: light
  networks:
    - ssid: !secret ssid-esphome-airport
      password: !secret password-esphome
    - ssid: !secret ssid-esphome
      password: !secret password-esphome
    - ssid: !secret ssid-esphome-backup
      password: !secret password-esphome

captive_portal:
  
logger: 
  level: DEBUG

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: false

bluetooth_proxy:
  active: true
    

switch:
  - platform: gpio
    pin:
      number: 19
      # inverted: yes
    name: "Vloerverwarming"
    id: pomp_vloerverwarming
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    pin:
      number: 25
      # inverted: yes
    name: "Warm water extra"
    id: extra
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    pin:
      number: 18
      # inverted: yes
    name: "Warm water snel"
    id: warm_water_snel
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: warm_water_snel
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    pin:
      number: 13
      # inverted: yes
    name: "Verwarming"
    id: verwarming
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    pin:
      number: 26
      # inverted: yes
    name: "Warm water"
    id: warm_water
    restore_mode: DISABLED
    # on_turn_on:
    #   - delay: 500ms
    #   - switch.turn_off: warm_water_snel
    # on_turn_off:
    # - homeassistant.service:
    #     service: input_boolean.turn_off
    #     data:
    #       entity_id: input_boolean.warm_water_2u, input_boolean.warm_water_3u, input_boolean.warm_water_4u, input_boolean.warm_water_5u

