substitutions:
  devicename: verwarming2
  upper_devicename: verwarming
  platform: esp32
  board: esp32dev

esp32:
  framework:
    type: esp-idf

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base_new_style.yaml

wifi:
  # ...
  power_save_mode: light
  use_address: 192.168.6.162

i2c:
  - sda: 21
    scl: 22
    scan: true
    id: bus_a
  # - id: bus_b
  #   sda: 14
  #   scl: 15
  #   scan: true

# sensor:
#   - platform: dht
#     pin: 32
#     model: DHT22
#     temperature:
#       accuracy_decimals: 1
#       name: "Waskot temperatuur"
#     humidity:
#       accuracy_decimals: 1
#       name: "Waskot luchtvochtigheid"
#     update_interval: 60s

pcf8574:
  - id: 'pcf8575_hub'
    address: 0x20
    pcf8575: true
    i2c_id: bus_a

# Individual outputs
switch:
  - platform: gpio
    pin:
      pcf8574: pcf8575_hub
      number: 0
      mode:
        output: true
      inverted: true
    name: "Reserve"
    restore_mode: RESTORE_DEFAULT_OFF
  
  - platform: gpio
    pin:
      pcf8574: pcf8575_hub
      number: 1
      mode:
        output: true
      inverted: true
    name: "Slaapkamer ${upper_devicename}"
    restore_mode: RESTORE_DEFAULT_OFF
  
  - platform: gpio
    pin:
      pcf8574: pcf8575_hub
      number: 2
      mode:
        output: true
      inverted: true
    name: "Badkamer ${upper_devicename}"
    restore_mode: RESTORE_DEFAULT_OFF
  
  - platform: gpio
    pin:
      pcf8574: pcf8575_hub
      number: 3
      mode:
        output: true
      inverted: true
    name: "Reserve_2"
    restore_mode: RESTORE_DEFAULT_OFF
  
  - platform: gpio
    pin:
      pcf8574: pcf8575_hub
      number: 4
      mode:
        output: true
      inverted: true
    name: "Bureau ${upper_devicename}"
    restore_mode: RESTORE_DEFAULT_OFF
  
  - platform: gpio
    pin:
      pcf8574: pcf8575_hub
      number: 5
      mode:
        output: true
      inverted: true
    name: "Slaapkamer Noor ${upper_devicename}"
    restore_mode: RESTORE_DEFAULT_OFF
  
  - platform: gpio
    pin:
      pcf8574: pcf8575_hub
      number: 6
      mode:
        output: true
      inverted: true
    name: "Wc ${upper_devicename}"
    restore_mode: RESTORE_DEFAULT_OFF
  
  - platform: gpio
    pin:
      pcf8574: pcf8575_hub
      number: 7
      mode:
        output: true
      inverted: true
    name: "Slaapkamer Fien ${upper_devicename}"
    restore_mode: RESTORE_DEFAULT_OFF
