

substitutions:
  devicename: tester
  # platform: esp8266
  # board: nodemcuv2
  upper_devicename: Tester
  # ssid: !secret ssid-waskot


# https://docs.cirkitdesigner.com/component/bf83b676-1f1f-45a8-a073-eda11fe8155a/module-ethernet-w5500


  platform: esp32
  board: esp32dev

esp32:
  framework:
    # type: arduino
    type: esp-idf

packages:
  # wifi: !include common/wifi.yaml
  device_base: !include common/device_base_new_style.yaml

ethernet:
  type: W5500
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
  cs_pin: GPIO33
  interrupt_pin: GPIO25
  # reset_pin: 
  # use_address: 192.168.79.220

i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: true
  - id: bus_b
    sda: 14
    scl: 15
    scan: true


switch:
  - platform: gpio
    pin:
      number: 32
      # number: 16
      inverted: yes
    name: ${upper_devicename}
    id: luchtdroger
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    pin:
      # number: 33
      number: 17
      # inverted: yes
    internal: true
    name: low
    id: low
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    pin:
      # number: 25
      number: 16
      # inverted: yes
    # internal: true
    name: Verluchting
    id: ventilator
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on: 
      then:
        - lambda: |-
            if ((id(living_luchtvochtigheid).state > 59) && (id(living_temperatuur).state < 21)) {
              id(luchtdroger).turn_on();
            }
            if ((id(temp_in).state > 1) && (id(ha_temp).state < 32) && (id(living_absolute_luchtvochtigheid).state > id(buiten_absolute_luchtvochtigheid).state) && (id(living_temperatuur).state < 21)) {
              id(luchtdroger).turn_on();
            } 
    
    on_turn_off: 
      then:
        - switch.turn_off: luchtdroger

  - platform: gpio
    pin:
      # number: 19
      number: 4
      inverted: yes
    internal: true
    id: reserve
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: homeassistant
    id: u
    internal: true
    entity_id: script.verluchting_1_uur
    on_press:
      then:
        - delay: 2h
        - switch.turn_off: ventilator
        # - fan.turn_off: ventilatie


  - platform: homeassistant
    id: uu
    internal: true
    entity_id: script.verluchting_2_uur
    on_press:
      then:
        - delay: 3h
        - switch.turn_off: ventilator
        # - fan.turn_off: ventilatie


sensor:
  # - platform: dht
  #   pin: 32
  #   model: DHT22
  #   temperature:
  #     accuracy_decimals: 1
  #     name: "Waskot temperatuur"
  #   humidity:
  #     accuracy_decimals: 1
  #     name: "Waskot luchtvochtigheid"
  #   update_interval: 60s
    
  - platform: sht3xd
    temperature:
      name: ${upper_devicename} uitgaande temperatuur
      # internal: true
    humidity:
      name: ${upper_devicename} uitgaande luchtvochtigheid
    # address: 0x44
    update_interval: 60s
    i2c_id: bus_a

  - platform: sht3xd
    temperature:
      name: ${upper_devicename} ingaande temperatuur
      id: temp_in
      on_value_range:
        - below: 3.0
          then:
            - switch.turn_off: luchtdroger
      # internal: true
    humidity:
      name: ${upper_devicename} ingaande luchtvochtigheid
    address: 0x44
    update_interval: 60s
    i2c_id: bus_b
  
  - platform: homeassistant
    entity_id: sensor.living_absolute_luchtvochtigheid
    id: living_absolute_luchtvochtigheid
    internal: true
  
  - platform: homeassistant
    entity_id: sensor.buiten_absolute_luchtvochtigheid
    id: buiten_absolute_luchtvochtigheid
    internal: true
  
  - platform: homeassistant
    entity_id: sensor.buiten_temperatuur
    id: ha_temp
    internal: true
  
  - platform: homeassistant
    entity_id: sensor.living_luchtvochtigheid
    id: living_luchtvochtigheid
    internal: true

  - platform: homeassistant
    entity_id: sensor.temperatuur_living
    id: living_temperatuur
    internal: true