alias: Knop Fien 4 klik
id: b0876a7a-d4f7-4627-984c-1d1eeb9cbc0a
triggers:
  - trigger: state
    entity_id: binary_sensor.knop_fien_4_klik
    to: 'on'
  - trigger: event
    event_type: state_changed
    event_data:
      entity_id: input_button.verwarming_1u_fien
    id: aan
  - trigger: time
    at: input_datetime.slaapkamer_fien_verwarming_end_time
    id: uit
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: aan
        sequence:
          - action: climate.set_preset_mode
            target:
              entity_id: climate.slaapkamer_fien
            data:
              preset_mode: boost
          - action: input_datetime.set_datetime
            data:
              datetime: >
                {{ now() + timedelta(seconds=3600) }}
            target:
              entity_id: input_datetime.slaapkamer_fien_verwarming_end_time
      - conditions:
          - condition: trigger
            id: uit
        sequence:
          - action: climate.set_preset_mode
            target:
              entity_id: climate.slaapkamer_fien
            data:
              preset_mode: >
                {{ state_attr('climate.slaapkamer', 'preset_mode') }}