alias: Knop Fien 2 klik
id: 9742a76c-726a-4f71-8eea-f61edcbf6812
triggers:
  - trigger: state
    entity_id: binary_sensor.knop_fien_2_klik
    to: "on"
    id: aan
  - trigger: time
    at: input_datetime.slaapkamer_fien_verwarming_end_time
    id: uit
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: aan
        sequence:
          - action: climate.set_preset_mode
            target:
              entity_id: climate.slaapkamer_fien
            data:
              preset_mode: boost
          - action: input_datetime.set_datetime
            data:
              datetime: >
                {{ now() + timedelta(seconds=3600) }}
            target:
              entity_id: input_datetime.slaapkamer_fien_verwarming_end_time
      - conditions:
          - condition: trigger
            id: uit
        sequence:
          - action: climate.set_preset_mode
            target:
              entity_id: climate.slaapkamer_fien
            data:
              preset_mode: >
                {{ state_attr('climate.slaapkamer', 'preset_mode') }}

