- binary_sensor:
    - name: Fotocel poort error
      unique_id: b45e3ce5-2f5f-4747-9a96-0254526cacbf
      icon: mdi:alert-circle-outline
      state: "{{ is_state('input_boolean.fotocel_poort_error', 'on') }}"
