hide_all: true
order:
  - item: Overzicht
    new_item: true
    icon: mdi:home
    order: 1
    href: "/lovelace/default_view"
    hide: false
#   - new_item: true
#     item: History explorer
#     href: "/history-explorer"
#     icon: mdi:history
#     order: 1
  - item: Kalenders
    new_item: true
    href: "/lovelace-kalender/kalenders"
    icon: mdi:calendar-star
    hide: false
    order: 2
  - item: Config
    bottom: true
    new_item: true
    icon: mdi:cog
    href: "/config/dashboard"
    hide: false
  # - divider: true
# extendable_configs:
#   martine:
#     extend_from: 'base'
#     order:
#       - item: todo
#         order: 3
#       - item: music-assistant
#         order: 4
#       - item: frigate
#         order: 5
#       - item: energy
#         order: 6
exceptions:
  - user: Martine
    extend_from: 'base'
    order:
      - item: to-do
        order: 3
        hide: false
      - item: Music assistant
        new_item: true
        href: "/app/d5369777_music_assistant_beta"
        icon: mdi:music
        order: 4
        hide: false
      - new_item: true
        item: Frigate
        icon: mdi:cctv
        href: "/app/ccab4aaf_frigate-proxy"
        order: 5
      - item: energie
        order: 6
        hide: false
      - item: Config
        bottom: true
        new_item: true
        icon: mdi:cog
        order: 7
        href: "/config/dashboard"
        hide: false
  - user: Giel
    hide_all: true
    order:
      - item: overview
        order: 1
        href: "/lovelace/default_view"
        hide: false
      - item: Kalenders
        new_item: true
        href: "/lovelace-kalender/kalenders"
        icon: mdi:calendar-star
        hide: false
        order: 2
      - item: to-do
        order: 3
        hide: false
      - item: Music assistant
        new_item: true
        href: "/app/d5369777_music_assistant_beta"
        icon: mdi:music
        order: 4
        hide: false
      - new_item: true
        item: Frigate
        icon: mdi:cctv
        href: "/app/ccab4aaf_frigate-proxy"
        order: 5
      - item: energy
        order: 6
        hide: false
      # - divider: true
      - new_item: true
        item: Emhass
        # href: "/app/local_emhass-async"
        href: "/app/5b918bf2_emhass"
        icon: mdi:home-lightning-bolt
        order: 7
      - new_item: true
        item: Adguard
        href: "/app/a0d7b954_adguard"
        icon: mdi:shield
        order: 8
        hide: false
      - item: hacs
        order: 9
        hide: false
        # notification: |
        #   [[[
        #     const outdatedHacsEntities = Object.values(entities.update).filter(
        #       (entity) => entity.platform === 'hacs' && is_state(entity.entity_id, 'on')
        #     );
        #     return outdatedHacsEntities.length || '';
        #   ]]]
      - item: Esphome
        new_item: true
        order: 10
        hide: false
        icon: mdi:car-esp
        href: "/app/5c53de3b_esphome"
      - item: History explorer
        new_item: true
        href: "/history-explorer"
        icon: mdi:history
        order: 11
        hide: false
      - item: Foutenboek
        # bottom: true
        href: "/config/logs"
        icon: mdi:math-log
        order: 12
        hide: false
      - item: developer tools
        name: Dev tools
        new_item: true
        icon: mdi:tools
        # bottom: true
        href: "/config/developer-tools/template"
        hide: false
        order: 13
      - item: logbook
        name: Logbook
        new_item: true
        icon: mdi:book-alert
        # bottom: true
        href: "/logbook"
        hide: false
        order: 14
      # - item: Config
      #   bottom: true
      #   new_item: true
      #   icon: mdi:cog
      #   order: 15
      #   href: "/config/dashboard"
      #   hide: false



#   - new_item: true
#     item: Energy
#     href: "/energy"
#     icon: mdi:flash
#     order: 3
#   - new_item: true
#     item: Adguard
#     href: "/a0d7b954_adguard/ingress"
#     icon: mdi:shield
#     order: 4
#   - new_item: true
#     item: Emhass
#     href: "/5b918bf2_emhass/ingress"
#     icon: mdi:home-lightning-bolt
#     order: 5
  # - item: hacs
  #   order: 7
#     # notification: |
#     #   [[[
#     #     const outdatedHacsEntities = Object.values(entities.update).filter(
#     #       (entity) => entity.platform === 'hacs' && is_state(entity.entity_id, 'on')
#     #     );
#     #     return outdatedHacsEntities.length || '';
#     #   ]]]
#   - new_item: true
#     item: Frigate
#     bottom: true
#     icon: mdi:cctv
#     href: "/ccab4aaf_frigate-proxy/ingress"
#     order: 7
#   - new_item: true
#     item: EspHome
#     href: "15ef4d2f_esphome/ingress"
#     icon: mdi:car-esp
#     bottom: true
#     order: 8
#   - item: logbook
#     bottom: true
#     order: 9
#   - new_item: true
#     item: Logs
#     bottom: true
#     href: "/config/logs"
#     icon: mdi:math-log
#     order: 10
#   - item: developer tools
#     name: Dev tools
#     icon: mdi:tools
#     bottom: true
#     order: 11
#   - item: history
#     hide: true
#   - item: snapshots
#     hide: true
#   - item: backups
#     hide: true
#   - item: map
#     hide: true
#   - item: media
#     hide: true
# exceptions:
#   - user:
#     - Fien
#     - Noor
#     order:
#       - item: overview
#         order: 0
#   # - user: Palaus
#   #   extend_from: base
#   #   order:
#   #     - item: history
#   #       order: 12
#   #     - item: media
#   #       order: 13
