# order:
#   - item: overview
#     order: 0
#   - new_item: true
#     item: History explorer
#     href: "/history-explorer"
#     icon: mdi:history
#     order: 1
#   - new_item: true
#     item: Kalenders
#     href: "/lovelace-kalender/kalenders"
#     icon: mdi:calendar-star
#     order: 2
#   - new_item: true
#     item: Energy
#     href: "/energy"
#     icon: mdi:flash
#     order: 3
#   - new_item: true
#     item: Adguard
#     href: "/a0d7b954_adguard/ingress"
#     icon: mdi:shield
#     order: 4
#   - new_item: true
#     item: Emhass
#     href: "/5b918bf2_emhass/ingress"
#     icon: mdi:home-lightning-bolt
#     order: 5
#   - item: hacs
#     order: 6
#     # notification: |
#     #   [[[
#     #     const outdatedHacsEntities = Object.values(entities.update).filter(
#     #       (entity) => entity.platform === 'hacs' && is_state(entity.entity_id, 'on')
#     #     );
#     #     return outdatedHacsEntities.length || '';
#     #   ]]]
#   - new_item: true
#     item: Frigate
#     bottom: true
#     icon: mdi:cctv
#     href: "/ccab4aaf_frigate-proxy/ingress"
#     order: 7
#   - new_item: true
#     item: EspHome
#     href: "15ef4d2f_esphome/ingress"
#     icon: mdi:car-esp
#     bottom: true
#     order: 8
#   - item: logbook
#     bottom: true
#     order: 9
#   - new_item: true
#     item: Logs
#     bottom: true
#     href: "/config/logs"
#     icon: mdi:math-log
#     order: 10
#   - item: developer tools
#     name: Dev tools
#     icon: mdi:tools
#     bottom: true
#     order: 11
#   - item: history
#     hide: true
#   - item: snapshots
#     hide: true
#   - item: backups
#     hide: true
#   - item: map
#     hide: true
#   - item: media
#     hide: true
# exceptions:
#   - user:
#     - Fien
#     - Noor
#     order:
#       - item: overview
#         order: 0
#   # - user: Palaus
#   #   extend_from: base
#   #   order:
#   #     - item: history
#   #       order: 12
#   #     - item: media
#   #       order: 13
