- trigger:
    - trigger: time_pattern
      # This will update every night
      hours: 23
      minutes: 59
      seconds: 30
  sensor:
    - name: "Degree day daily"
      unique_id: 3643a5c6-2fd0-4f4e-b980-cbd8a3181372
      unit_of_measurement: "DD"
      state: >
        {{ states('sensor.degree_day') }}

    - name: "Branduren warmtepomp vandaag"
      unique_id: 471b41b7-3226-4156-a7a9-d151debadbf6
      unit_of_measurement: "uren"
      state: >
        {{ states('sensor.branduren_warmtepomp') }}
