- trigger:
    - platform: state
      entity_id: sensor.huidige_opbrengst
    - platform: state
      entity_id: sensor.solcast_solaredge_power_now
  sensor:
    - name: Pv estimate
      unique_id: 3509ef1a-89c5-4d3f-ba51-0c78cea0dfb2
      state: >
        {%- set real = states('sensor.huidige_opbrengst') | float(0) %}
        {%- set percent = real / 3.3 %}
        {%- set solcast = states('sensor.solcast_solaredge_power_now') | float(0) %}
        {% if real and solcast > 0 %}
          {% if real > solcast + percent %}
            pv_estimate90(more)
          {% elif real < solcast - percent %}
            pv_estimate10(less)
          {% else %}
            pv_estimate
          {% endif %}
        {% else %}
          pv_estimate
        {% endif %}

- trigger:
    - platform: state
      entity_id: sensor.solaredge_inverter_watthours
  sensor:
    - name: "SolarEdge energy"
      unique_id: f7e4ae3b-cb83-4e93-8955-c681d4025ea6
      icon: "mdi:counter"
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total_increasing
      state: >
        {% set current_value = states('sensor.solaredge_energy') | float(0) %}
        {% set source_state = states('sensor.solaredge_inverter_watthours') %}
        {% if source_state in ['unavailable', 'unknown', None] %}
          {{ current_value }}
        {% else %}
          {% set new_value = (states('sensor.solaredge_inverter_watthours') | float(0) / 1000) | round(2) %}
          {{ current_value if new_value < current_value else new_value }}
        {% endif %}