substitutions:
  name: m5living
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: XKpbiM+eAgSS5IeHfudiPR+cxv7LbK1aemdAX61pPcY=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
