adguard_off_3u:
  sequence:
    - action: switch.turn_off
      entity_id: switch.adguard_protection
    - delay:
        minutes: 180
    - action: switch.turn_on
      entity_id: switch.adguard_protection
