douchen_giel:
  sequence:
    - action: media_player.volume_set
      data_template:
        entity_id: media_player.mass_badkamer
        volume_level: 0.40
    - action: script.random_music
      data:
        sonos_entity: media_player.mass_badkamer

    - action: script.turn_on
      target:
        entity_id: script.verluchting_2_uur
