random_playlist:
  sequence:
    - action: todo.get_items
      data:
        status: needs_action
      target:
        entity_id: todo.playlists
      response_variable: playlists
    - variables:
        playlist: >
          {% set playlist = playlists['todo.playlists']['items'] | list -%}
          {{ playlist | random }}

    - action: media_player.unjoin
      target:
        entity_id: media_player.mass_badkamer
    - action: music_assistant.play_media
      data:
        enqueue: replace
        media_type: playlist
        media_id: >
          {{ playlist.summary }}
      target:
        entity_id: >
          {{ sonos_entity }}
    - action: media_player.shuffle_set
      data:
        shuffle: true
      target:
        entity_id: >
          {{ sonos_entity }}
    - action: todo.update_item
      target:
        entity_id:
          - todo.playlists
      data:
        status: completed
        item: >
          {{ playlist.uid }}
    - action: input_text.set_value
      target:
        entity_id: input_text.random_muziek
      data:
        value: >
          {{ playlist.summary }}
