random_radio:
  sequence:
    - action: todo.get_items
      data:
        status: needs_action
      target:
        entity_id: todo.radio_stations
      response_variable: radios
    - variables:
        radio: >
          {% set radio = radios['todo.radio_stations']['items'] | list -%}
          {{ radio | random }}

    - action: media_player.unjoin
      target:
        entity_id: media_player.mass_badkamer
    - action: music_assistant.play_media
      data:
        enqueue: replace
        media_type: radio
        media_id: >
          {{ radio.summary }}
      target:
        entity_id: >
          {{ sonos_entity }}
    - action: media_player.shuffle_set
      data:
        shuffle: false
      target:
        entity_id: >
          {{ sonos_entity }}
    - action: todo.update_item
      target:
        entity_id:
          - todo.radio_stations
      data:
        status: completed
        item: >
          {{ radio.uid }}
    - action: input_text.set_value
      target:
        entity_id: input_text.random_muziek
      data:
        value: >
          {{ radio.summary }}
