sonos_spreek:
  sequence:
    - action: tts.cloud_say
      data:
        entity_id: >
          {% if is_state('input_select.welke_sonos', 'Keuken') -%}
            media_player.mass_keuken
          {% elif is_state('input_select.welke_sonos', 'Badkamer') -%}
            media_player.mass_badkamer
          {% elif is_state('input_select.welke_sonos', 'Living') -%}
            media_player.mass_living_2
          {% elif is_state('input_select.welke_sonos', 'Move') -%}
            media_player.mass_move
          {% elif is_state('input_select.welke_sonos', 'Noor') -%}
            media_player.mass_slaapkamer_noor
          {% elif is_state('input_select.welke_sonos', 'Fien') -%}
            media_player.mass_slaapkamer_fien
          {% else -%}
            False
          {% endif -%}
        cache: false
        message: >
          {% set message =  states('input_text.sonos_spraak') -%}
            {{message}}
